import type { CodeSymbol } from "../indexer/symbol.types.js";
import type { DetectedPattern } from "../patterns/patternAnalyzer.js";
import type { RelationshipRow } from "../storage/db.js";
import {
  fileSlug,
  buildMermaidForSymbol,
  buildMermaidForFile,
  buildMermaidOverview,
  buildMermaidTopConnected,
} from "./shared.js";

export { fileSlug };

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function escapeCodeBlocks(str: string): string {
  return escapeHtml(str);
}

function badgeClass(kind: string): string {
  const base = "px-2 py-0.5 rounded text-xs font-medium border";
  const map: Record<string, string> = {
    class: "bg-blue-50 text-blue-700 border-blue-200",
    abstract_class: "bg-blue-50 text-blue-700 border-blue-200 dashed",
    interface: "bg-green-50 text-green-700 border-green-200",
    function: "bg-yellow-50 text-yellow-800 border-yellow-200",
    method: "bg-purple-50 text-purple-700 border-purple-200",
    enum: "bg-pink-50 text-pink-700 border-pink-200",
    type: "bg-indigo-50 text-indigo-700 border-indigo-200",
  };
  return `${base} ${map[kind] || "bg-gray-50 text-gray-700 border-gray-200"}`;
}

function visibilityBadge(visibility?: string): string {
  if (!visibility) return "";
  const base = "px-2 py-0.5 rounded text-xs font-medium border ml-2";
  const map: Record<string, string> = {
    public: "bg-green-50 text-green-700 border-green-200",
    protected: "bg-yellow-50 text-yellow-800 border-yellow-200",
    private: "bg-red-50 text-red-700 border-red-200",
  };
  return `<span class="${base} ${map[visibility] || "bg-gray-50 text-gray-700 border-gray-200"}">${visibility}</span>`;
}

function layerBadge(layer?: string): string {
  if (!layer) return "";
  const base = "px-2 py-0.5 rounded text-xs font-medium border ml-2";
  const map: Record<string, string> = {
    domain: "bg-green-50 text-green-700 border-green-200",
    application: "bg-blue-50 text-blue-700 border-blue-200",
    infrastructure: "bg-yellow-50 text-yellow-800 border-yellow-200",
    presentation: "bg-purple-50 text-purple-700 border-purple-200",
    test: "bg-gray-50 text-gray-700 border-gray-200",
  };
  return `<span class="${base} ${map[layer] || "bg-gray-50 text-gray-700 border-gray-200"}">${layer}</span>`;
}

function statusBadges(symbol: CodeSymbol): string {
  const badges = [];
  if (symbol.exported) {
    badges.push(`<span class="px-2 py-0.5 rounded text-xs font-medium border bg-blue-50 text-blue-700 border-blue-200 ml-2">exported</span>`);
  }
  if (symbol.deprecated) {
    badges.push(`<span class="px-2 py-0.5 rounded text-xs font-medium border bg-red-50 text-red-700 border-red-200 ml-2 line-through">deprecated</span>`);
  }
  return badges.join("");
}

function violationsBadges(symbol: CodeSymbol, governanceHref = "governance.html"): string {
  if (!symbol.violations?.length) return "";
  return symbol.violations
    .map(
      (v) =>
        `<a href="${governanceHref}#reaper" class="px-2 py-0.5 rounded text-xs font-medium border bg-amber-50 text-amber-800 border-amber-200 ml-2 hover:bg-amber-100">${escapeHtml(v)}</a>`,
    )
    .join("");
}

function layout(
  title: string,
  currentPage: string,
  body: string,
  depth = 0,
  facetsHtml = "",
): string {
  const prefix = depth > 0 ? "../".repeat(depth) : "";
  const navLinks = [
    [`${prefix}index.html`, "Dashboard"],
    [`${prefix}files.html`, "Files"],
    [`${prefix}relationships.html`, "Relationships"],
    [`${prefix}patterns.html`, "Patterns"],
  ];

  const sidebarNav = navLinks
    .map(([href, label]) => {
      const isActive = currentPage === href.split("/").pop();
      return `<a href="${href}" class="block px-4 py-2 rounded-md text-sm font-medium ${isActive
          ? "bg-blue-50 text-blue-700"
          : "text-gray-700 hover:bg-gray-50 hover:text-gray-900"}">${label}</a>`;
    })
    .join("");

  const rightSidebar = `
    <aside class="w-64 bg-white border-l border-gray-200 p-6 overflow-y-auto hidden xl:block flex-shrink-0">
      ${facetsHtml ? `<div class="mb-8">${facetsHtml}</div>` : ""}
      <div id="on-this-page-wrap">
        <h3 class="px-3 text-xs font-semibold text-gray-500 uppercase tracking-wider mb-2">On this page</h3>
        <nav id="on-this-page" class="space-y-1 text-sm" aria-label="On this page"></nav>
      </div>
    </aside>`;

  return `<!DOCTYPE html>
<html lang="en" class="h-full bg-gray-50">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(title)} - docs-kit</title>
  <meta name="description" content="Documentation generated by docs-kit for your codebase">
  <script src="https://cdn.tailwindcss.com?plugins=typography"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/github.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js"></script>
  <script>
    tailwind.config = {
      theme: {
        extend: {
          colors: {
            primary: '#2563eb',
            secondary: '#475569',
          }
        }
      }
    }
  </script>
</head>
<body class="h-full flex flex-col">
  <header class="bg-white border-b border-gray-200 sticky top-0 z-30">
    <div class="max-w-8xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="flex justify-between h-16">
        <div class="flex">
          <div class="flex-shrink-0 flex items-center">
            <span class="text-xl font-bold text-blue-600">docs-kit</span>
          </div>
        </div>
        <div class="flex-1 flex items-center justify-center px-2 lg:ml-6 lg:justify-end">
          <div class="max-w-lg w-full lg:max-w-xs relative" id="global-search-wrap">
            <label for="global-search" class="sr-only">Search</label>
            <div class="relative">
              <input id="global-search" class="block w-full pl-3 pr-3 py-2 border border-gray-300 rounded-md leading-5 bg-white placeholder-gray-500 focus:outline-none focus:placeholder-gray-400 focus:ring-1 focus:ring-blue-500 focus:border-blue-500 sm:text-sm" placeholder="Search symbols..." type="search" autocomplete="off" aria-expanded="false" aria-haspopup="listbox" aria-controls="global-search-results">
              <div id="global-search-results" role="listbox" class="absolute left-0 right-0 mt-1 bg-white border border-gray-200 rounded-md shadow-lg max-h-80 overflow-auto z-50 hidden" aria-label="Search results"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>

  <div class="flex-1 flex overflow-hidden">
    <aside class="w-64 bg-white border-r border-gray-200 overflow-y-auto hidden md:block flex-shrink-0">
      <div class="p-6">
        <h3 class="px-3 text-xs font-semibold text-gray-500 uppercase tracking-wider mb-2">Navigation</h3>
        <nav class="space-y-1">
          ${sidebarNav}
        </nav>
        
        <h3 class="px-3 text-xs font-semibold text-gray-500 uppercase tracking-wider mt-8 mb-2">Documentation</h3>
        <nav class="space-y-1">
          <a href="${prefix}docs.html" class="block px-4 py-2 rounded-md text-sm font-medium text-gray-700 hover:bg-gray-50 hover:text-gray-900">Docs</a>
        </nav>

        <h3 class="px-3 text-xs font-semibold text-gray-500 uppercase tracking-wider mt-8 mb-2">Health</h3>
        <nav class="space-y-1">
          <a href="${prefix}deprecated.html" class="block px-4 py-2 rounded-md text-sm font-medium text-gray-700 hover:bg-gray-50 hover:text-gray-900">Deprecated</a>
          <a href="${prefix}governance.html" class="block px-4 py-2 rounded-md text-sm font-medium text-gray-700 hover:bg-gray-50 hover:text-gray-900">Violations</a>
          <a href="${prefix}index.html#high-impact-symbols" class="block px-4 py-2 rounded-md text-sm font-medium text-gray-700 hover:bg-gray-50 hover:text-gray-900">High impact</a>
        </nav>

        <h3 class="px-3 text-xs font-semibold text-gray-500 uppercase tracking-wider mt-8 mb-2">Quick Links</h3>
        <nav class="space-y-1">
          <a href="${prefix}index.html#architecture-overview" class="block px-4 py-2 rounded-md text-sm font-medium text-gray-700 hover:text-gray-50 hover:text-gray-900">Architecture</a>
          <a href="${prefix}index.html#architecture-layers" class="block px-4 py-2 rounded-md text-sm font-medium text-gray-700 hover:bg-gray-50 hover:text-gray-900">Layers</a>
          <a href="${prefix}index.html#top-complex-symbols" class="block px-4 py-2 rounded-md text-sm font-medium text-gray-700 hover:bg-gray-50 hover:text-gray-900">Complexity</a>
          <a href="${prefix}relationships.html" class="block px-4 py-2 rounded-md text-sm font-medium text-gray-700 hover:bg-gray-50 hover:text-gray-900">All Relationships</a>
        </nav>
      </div>
    </aside>

    <main class="flex-1 overflow-y-auto focus:outline-none p-6 lg:p-8" id="content" role="main">
      <div class="max-w-7xl mx-auto">
        ${body}
      </div>
    </main>

    ${rightSidebar}
  </div>

  <script>
    (function() {
      function slugify(text) {
        return text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
      }
      var main = document.getElementById('content');
      var nav = document.getElementById('on-this-page');
      var wrap = document.getElementById('on-this-page-wrap');
      if (!main || !nav || !wrap) return;
      var headings = main.querySelectorAll('h2, h3');
      if (headings.length === 0) { wrap.style.display = 'none'; return; }
      var html = '';
      headings.forEach(function(h) {
        var id = h.id || slugify(h.textContent || '');
        if (!h.id) h.id = id;
        var indent = h.tagName === 'H3' ? ' pl-3' : '';
        html += '<a href="#' + id + '" class="block px-3 py-1 rounded-md text-gray-600 hover:bg-gray-50 hover:text-gray-900' + indent + '">' + (h.textContent || '').replace(/</g, '&lt;') + '</a>';
      });
      nav.innerHTML = html;
    })();

    // Deep link to folder in File Explorer: open ancestor details and scroll
    (function() {
      var hash = location.hash;
      if (!hash || !hash.startsWith('#dir-')) return;
      var el = document.getElementById(hash.slice(1));
      if (!el) return;
      var p = el.parentElement;
      while (p) {
        if (p.tagName === 'DETAILS') p.setAttribute('open', '');
        p = p.parentElement;
      }
      el.scrollIntoView({ behavior: 'smooth', block: 'center' });
    })();
  </script>

  <footer class="bg-white border-t border-gray-200 py-4 px-6 text-center text-sm text-gray-500">
    Generated by docs-kit
  </footer>

  <script src="https://cdn.jsdelivr.net/npm/fuse.js@6.6.2/dist/fuse.min.js"></script>
  <script>
    var INDEX = null;
    var FUSE = null;

    // Load search index
    fetch('${prefix}search.json')
      .then(function (r) { return r.json(); })
      .then(function (data) {
        if (Array.isArray(data)) {
          INDEX = { items: data };
        } else {
          INDEX = data;
        }
        try {
          FUSE = new Fuse(INDEX.items, { keys: [{ name: 'name', weight: 0.6 }, { name: 'signature', weight: 0.2 }, { name: 'summary', weight: 0.2 }], includeMatches: true, threshold: 0.35 });
        } catch (e) { console.warn('Fuse init failed', e); FUSE = null; }
      });

    // Global search dropdown
    (function() {
      var input = document.getElementById('global-search');
      var panel = document.getElementById('global-search-results');
      var selectedIdx = -1;

      function hide() {
        panel.classList.add('hidden');
        panel.innerHTML = '';
        selectedIdx = -1;
        input.setAttribute('aria-expanded', 'false');
      }

      function show(items) {
        if (!items || items.length === 0) { hide(); return; }
        var html = '';
        items.slice(0, 10).forEach(function(it, i) {
          var href = it.id ? ('symbols/' + it.id + '.html') : '#';
          html += '<a role="option" id="search-opt-' + i + '" class="block px-4 py-2 text-sm text-left hover:bg-blue-50 focus:bg-blue-50 focus:outline-none border-b border-gray-100 last:border-0" href="' + href + '" tabindex="-1">' +
            '<span class="font-medium text-blue-600">' + (it.name || '').replace(/</g, '&lt;') + '</span>' +
            (it.kind ? ' <span class="text-gray-500 text-xs">' + it.kind + '</span>' : '') +
            (it.file ? '<br><span class="text-gray-400 text-xs">' + it.file + '</span>' : '') +
            '</a>';
        });
        panel.innerHTML = html;
        panel.classList.remove('hidden');
        input.setAttribute('aria-expanded', 'true');
        selectedIdx = 0;
        var first = document.getElementById('search-opt-0');
        if (first) first.classList.add('bg-blue-50');
      }

      function getResults() {
        var q = input.value.trim();
        if (!q || !FUSE) return [];
        return FUSE.search(q).map(function(r) { return r.item; });
      }

      function navigate(step) {
        var opts = panel.querySelectorAll('[role="option"]');
        if (opts.length === 0) return;
        opts[selectedIdx].classList.remove('bg-blue-50');
        selectedIdx = selectedIdx + step;
        if (selectedIdx < 0) selectedIdx = opts.length - 1;
        if (selectedIdx >= opts.length) selectedIdx = 0;
        opts[selectedIdx].classList.add('bg-blue-50');
        opts[selectedIdx].focus();
      }

      input.addEventListener('input', function() {
        var items = getResults();
        show(items);
      });

      input.addEventListener('focus', function() {
        if (panel.innerHTML) panel.classList.remove('hidden');
      });

      input.addEventListener('keydown', function(e) {
        if (e.key === 'Escape') { hide(); e.preventDefault(); return; }
        if (!panel.classList.contains('hidden') && panel.children.length) {
          if (e.key === 'ArrowDown') { navigate(1); e.preventDefault(); return; }
          if (e.key === 'ArrowUp') { navigate(-1); e.preventDefault(); return; }
          if (e.key === 'Enter' && selectedIdx >= 0) {
            var opt = document.getElementById('search-opt-' + selectedIdx);
            if (opt) { opt.click(); e.preventDefault(); }
          }
        }
      });

      document.addEventListener('click', function(e) {
        var wrap = document.getElementById('global-search-wrap');
        if (wrap && !wrap.contains(e.target)) hide();
      });

      panel.addEventListener('mousedown', function(e) {
        e.preventDefault();
      });

      document.addEventListener('keydown', function(e) {
        if (e.key !== '/' || e.ctrlKey || e.metaKey || e.altKey) return;
        var tag = (e.target && e.target.tagName) ? e.target.tagName.toLowerCase() : '';
        if (tag === 'input' || tag === 'textarea' || (e.target && e.target.isContentEditable)) return;
        e.preventDefault();
        input.focus();
      });
    })();
  </script>
</body>
</html>`;
}

function formatDate(d?: Date): string | undefined {
  if (!d) return undefined;
  try {
    return d.toISOString();
  } catch {
    return String(d);
  }
}

export interface ArchViolationRow {
  rule: string;
  file: string;
  symbol_id: string | null;
  message: string;
  severity: string;
}

export interface ReaperFindingRow {
  type: string;
  target: string;
  reason: string;
  suggested_action: string;
}

export interface SiteData {
  symbols: CodeSymbol[];
  relationships: RelationshipRow[];
  patterns: DetectedPattern[];
  files: string[];
  archViolations?: ArchViolationRow[];
  reaperFindings?: ReaperFindingRow[];
  /** ISO date string when the site was generated */
  generatedAt?: string;
}

export function renderMarkdownWrapper(title: string, mdFilename: string): string {
  const body = `
    <article id="doc" class="prose max-w-none prose-blue">
       <div class="flex items-center justify-center h-32">
          <svg class="animate-spin h-8 w-8 text-blue-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
            <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
            <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
          </svg>
          <span class="ml-2 text-gray-600">Loading document...</span>
       </div>
    </article>
    <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
    <script>
      (async function(){
        try {
          const res = await fetch('./${escapeHtml(mdFilename)}');
          if (!res.ok) throw new Error('Failed to load');
          const md = await res.text();
          const html = marked.parse(md);
          document.getElementById('doc').innerHTML = html;
          // Convert internal .md links to .html so navigation stays within site
          document.querySelectorAll('#doc a').forEach(function(a){
            const href = a.getAttribute('href');
            if (!href) return;
            if (href.toLowerCase().endsWith('.md')) a.setAttribute('href', href.slice(0, -3) + '.html');
          });
          hljs.highlightAll();
        } catch(e) {
          document.getElementById('doc').innerHTML = '<div class="bg-red-50 border border-red-200 rounded-md p-4 text-red-700">Error loading document: ' + e.message + '</div>';
        }
      })();
    </script>
  `;

  return layout(title, "", body, 1);
}

export function renderDashboard(data: SiteData): string {
  const { symbols, relationships, patterns, files, archViolations = [], reaperFindings = [], generatedAt } = data;

  const kindCounts: Record<string, number> = {};
  for (const s of symbols) {
    kindCounts[s.kind] = (kindCounts[s.kind] ?? 0) + 1;
  }

  // Layer counts
  const layerCounts: Record<string, number> = {};
  for (const s of symbols) {
    const layer = s.layer || "unknown";
    layerCounts[layer] = (layerCounts[layer] ?? 0) + 1;
  }

  // Top complex symbols
  const complexSymbols = symbols
    .filter((s) => s.metrics?.cyclomaticComplexity)
    .sort((a, b) => (b.metrics!.cyclomaticComplexity || 0) - (a.metrics!.cyclomaticComplexity || 0))
    .slice(0, 10);

  // Group files by directory
  const dirGroups: Record<string, { files: string[]; symbols: number }> = {};
  const dirKindBreakdown: Record<string, Record<string, number>> = {};
  for (const file of files) {
    const dir = file.split("/")[0] || "root";
    if (!dirGroups[dir]) dirGroups[dir] = { files: [], symbols: 0 };
    dirGroups[dir].files.push(file);
  }
  for (const symbol of symbols) {
    const dir = symbol.file.split("/")[0] || "root";
    if (dirGroups[dir]) dirGroups[dir].symbols++;
    if (!dirKindBreakdown[dir]) dirKindBreakdown[dir] = {};
    dirKindBreakdown[dir][symbol.kind] = (dirKindBreakdown[dir][symbol.kind] ?? 0) + 1;
  }

  // Overview graph
  const overviewGraph = buildMermaidOverview(symbols, relationships, true);

  const topLevel = symbols.filter((s) => !s.parent);

  // Deprecated symbols (top-level only for clarity)
  const deprecatedSymbols = topLevel.filter((s) => s.deprecated);

  // High-impact: symbols with most incoming relationships (top 10)
  const incomingCount = new Map<string, number>();
  for (const r of relationships) {
    incomingCount.set(r.target_id, (incomingCount.get(r.target_id) ?? 0) + 1);
  }
  const highImpactSymbols = symbols
    .filter((s) => (incomingCount.get(s.id) ?? 0) > 0)
    .sort((a, b) => (incomingCount.get(b.id) ?? 0) - (incomingCount.get(a.id) ?? 0))
    .slice(0, 10);

  const generatedLabel = generatedAt
    ? (() => {
        try {
          const d = new Date(generatedAt);
          return d.toLocaleDateString(undefined, { dateStyle: "medium" }) + " " + d.toLocaleTimeString(undefined, { hour: "2-digit", minute: "2-digit" });
        } catch {
          return generatedAt;
        }
      })()
    : "";
  const highComplexityCount = symbols.filter((s) => (s.metrics?.cyclomaticComplexity ?? 0) > 10).length;

  const body = `
    <div class="flex flex-wrap items-center justify-between gap-4 mb-6 pb-4 border-b border-gray-200">
      <h1 class="text-3xl font-bold text-gray-900">docs-kit Documentation</h1>
      ${generatedLabel ? `<p class="text-sm text-gray-500" title="Index build time">Generated: ${escapeHtml(generatedLabel)}</p>` : ""}
    </div>

    ${deprecatedSymbols.length > 0 || archViolations.length > 0 || highComplexityCount > 0
      ? `
    <div class="flex flex-wrap gap-3 mb-8 p-4 bg-gray-50 rounded-lg border border-gray-200">
      <span class="text-sm font-medium text-gray-700">Health:</span>
      ${deprecatedSymbols.length > 0 ? `<a href="#deprecated-symbols" class="inline-flex items-center px-3 py-1 rounded-full text-xs font-medium bg-amber-100 text-amber-800 border border-amber-200 hover:bg-amber-200">${deprecatedSymbols.length} deprecated</a>` : ""}
      ${archViolations.length > 0 ? `<a href="#arch-violations" class="inline-flex items-center px-3 py-1 rounded-full text-xs font-medium bg-red-100 text-red-800 border border-red-200 hover:bg-red-200">${archViolations.length} violations</a>` : ""}
      ${highComplexityCount > 0 ? `<a href="#top-complex-symbols" class="inline-flex items-center px-3 py-1 rounded-full text-xs font-medium bg-orange-100 text-orange-800 border border-orange-200 hover:bg-orange-200">${highComplexityCount} high complexity</a>` : ""}
    </div>`
      : ""}

    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-12">
      <div class="bg-white overflow-hidden shadow rounded-lg">
        <div class="px-4 py-5 sm:p-6 text-center">
          <dt class="text-sm font-medium text-gray-500 truncate">Files</dt>
          <dd class="mt-1 text-3xl font-semibold text-blue-600">${files.length}</dd>
        </div>
      </div>
      <div class="bg-white overflow-hidden shadow rounded-lg">
        <div class="px-4 py-5 sm:p-6 text-center">
          <dt class="text-sm font-medium text-gray-500 truncate">Symbols</dt>
          <dd class="mt-1 text-3xl font-semibold text-blue-600">${symbols.length}</dd>
        </div>
      </div>
      <div class="bg-white overflow-hidden shadow rounded-lg">
        <div class="px-4 py-5 sm:p-6 text-center">
          <dt class="text-sm font-medium text-gray-500 truncate">Relationships</dt>
          <dd class="mt-1 text-3xl font-semibold text-blue-600">${relationships.length}</dd>
        </div>
      </div>
      <div class="bg-white overflow-hidden shadow rounded-lg">
        <div class="px-4 py-5 sm:p-6 text-center">
          <dt class="text-sm font-medium text-gray-500 truncate">Patterns</dt>
          <dd class="mt-1 text-3xl font-semibold text-blue-600">${patterns.length}</dd>
        </div>
      </div>
    </div>

    ${deprecatedSymbols.length > 0
      ? `
    <div id="deprecated-symbols" class="mb-12">
      <h2 class="text-2xl font-bold text-gray-900 mb-6">Deprecated Symbols</h2>
      <div class="bg-white shadow overflow-x-auto sm:rounded-lg border border-gray-200">
        <table class="min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Name</th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Kind</th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">File</th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">
            ${deprecatedSymbols
              .sort((a, b) => a.name.localeCompare(b.name))
              .map(
                (s) => `<tr>
                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-blue-600"><a href="symbols/${s.id}.html" class="hover:underline">${escapeHtml(s.name)}</a></td>
                <td class="px-6 py-4 whitespace-nowrap text-sm"><span class="${badgeClass(s.kind)}">${s.kind}</span></td>
                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500"><a href="files/${fileSlug(s.file)}.html" class="hover:text-blue-600 hover:underline">${escapeHtml(s.file)}</a></td>
              </tr>`,
              )
              .join("")}
          </tbody>
        </table>
      </div>
      <p class="mt-2 text-sm text-gray-500"><a href="deprecated.html" class="text-blue-600 hover:underline">View all deprecated</a></p>
    </div>`
      : ""}

    ${highImpactSymbols.length > 0
      ? `
    <div id="high-impact-symbols" class="mb-12">
      <h2 class="text-2xl font-bold text-gray-900 mb-6">High-Impact Symbols</h2>
      <p class="text-sm text-gray-600 mb-4">Symbols with the most dependents. Changing these may affect many callers.</p>
      <div class="bg-white shadow overflow-x-auto sm:rounded-lg border border-gray-200">
        <table class="min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Name</th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">File</th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Dependents</th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">
            ${highImpactSymbols
              .map((s) => {
                const count = incomingCount.get(s.id) ?? 0;
                return `<tr>
                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-blue-600"><a href="symbols/${s.id}.html" class="hover:underline">${escapeHtml(s.name)}</a></td>
                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500"><a href="files/${fileSlug(s.file)}.html" class="hover:text-blue-600 hover:underline">${escapeHtml(s.file)}</a></td>
                <td class="px-6 py-4 whitespace-nowrap text-sm font-semibold text-gray-900">${count}</td>
              </tr>`;
              })
              .join("")}
          </tbody>
        </table>
      </div>
    </div>`
      : ""}

    ${archViolations.length > 0
      ? `
    <div id="arch-violations" class="mb-12">
      <h2 class="text-2xl font-bold text-gray-900 mb-6">Architecture Violations</h2>
      <p class="text-sm text-gray-600 mb-4"><a href="governance.html#arch" class="text-blue-600 hover:underline">View all</a></p>
      <div class="bg-white shadow overflow-x-auto sm:rounded-lg border border-gray-200">
        <table class="min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Rule</th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">File</th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Severity</th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Message</th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">
            ${archViolations
              .slice(0, 10)
              .map(
                (v) => `<tr>
                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">${escapeHtml(v.rule)}</td>
                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">${escapeHtml(v.file)}</td>
                <td class="px-6 py-4 whitespace-nowrap text-sm"><span class="px-2 py-0.5 rounded text-xs font-medium ${v.severity === "error" ? "bg-red-100 text-red-800" : "bg-yellow-100 text-yellow-800"}">${escapeHtml(v.severity)}</span></td>
                <td class="px-6 py-4 text-sm text-gray-600">${escapeHtml(v.message)}</td>
              </tr>`,
              )
              .join("")}
          </tbody>
        </table>
      </div>
    </div>`
      : ""}

    ${reaperFindings.length > 0
      ? `
    <div id="reaper-findings" class="mb-12">
      <h2 class="text-2xl font-bold text-gray-900 mb-6">Code Quality (Reaper)</h2>
      <p class="text-sm text-gray-600 mb-4"><a href="governance.html#reaper" class="text-blue-600 hover:underline">View all</a></p>
      <div class="bg-white shadow overflow-x-auto sm:rounded-lg border border-gray-200">
        <table class="min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Type</th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Target</th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Action</th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Reason</th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">
            ${reaperFindings
              .slice(0, 10)
              .map(
                (f) => `<tr>
                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">${escapeHtml(f.type)}</td>
                <td class="px-6 py-4 whitespace-nowrap text-sm text-blue-600"><a href="symbols/${escapeHtml(f.target)}.html" class="hover:underline">${escapeHtml(f.target)}</a></td>
                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">${escapeHtml(f.suggested_action)}</td>
                <td class="px-6 py-4 text-sm text-gray-600">${escapeHtml(f.reason)}</td>
              </tr>`,
              )
              .join("")}
          </tbody>
        </table>
      </div>
    </div>`
      : ""}

    <div id="architecture-layers" class="mb-12">
      <h2 class="text-2xl font-bold text-gray-900 mb-6">Architecture Layers</h2>
      ${(() => {
        const layerEntries = Object.entries(layerCounts).sort((a, b) => b[1] - a[1]);
        const maxLayer = Math.max(1, ...layerEntries.map(([, c]) => c));
        return `
      <div class="space-y-3 max-w-2xl mb-4">
        ${layerEntries
          .map(
            ([layer, count]) => `
        <div class="flex items-center gap-3">
          <span class="text-sm font-medium text-gray-700 capitalize w-24 flex-shrink-0">${layer}</span>
          <div class="flex-1 h-6 bg-gray-100 rounded overflow-hidden" title="${count} symbols">
            <div class="h-full bg-blue-500 rounded" style="width:${Math.round((count / maxLayer) * 100)}%"></div>
          </div>
          <span class="text-sm font-semibold text-gray-900 w-10 text-right">${count}</span>
        </div>`,
          )
          .join("")}
      </div>
      <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-4">
        ${layerEntries
          .map(
            ([layer, count]) => `
          <div class="bg-white overflow-hidden shadow rounded-lg border border-gray-200">
            <div class="px-4 py-5 sm:p-6 text-center">
              <dt class="text-sm font-medium text-gray-500 truncate capitalize">${layer}</dt>
              <dd class="mt-1 text-2xl font-semibold text-gray-900">${count}</dd>
            </div>
          </div>`,
          )
          .join("")}
      </div>`;
      })()}
    </div>

    <div class="mb-12" id="architecture-overview">
      <h2 class="text-2xl font-bold text-gray-900 mb-4">Architecture Overview</h2>
      ${overviewGraph ? `
      <div class="flex gap-2 mb-4" role="tablist" aria-label="Overview view">
        <button type="button" id="arch-tab-graph" role="tab" aria-selected="true" aria-controls="arch-panel-graph" class="arch-tab px-4 py-2 rounded-md text-sm font-medium bg-blue-100 text-blue-800 border border-blue-200">Graph</button>
        <button type="button" id="arch-tab-dirs" role="tab" aria-selected="false" aria-controls="arch-panel-dirs" class="arch-tab px-4 py-2 rounded-md text-sm font-medium text-gray-600 hover:bg-gray-100 border border-transparent">Directory map</button>
      </div>
      <div id="arch-panel-graph" role="tabpanel" class="arch-panel bg-white shadow rounded-lg p-6 overflow-x-auto border border-gray-200">
        <div class="mermaid">${overviewGraph}</div>
      </div>` : ""}
      <div id="arch-panel-dirs" role="tabpanel" class="arch-panel grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4 ${overviewGraph ? "hidden" : ""}" aria-hidden="${overviewGraph ? "true" : "false"}">
        ${Object.entries(dirGroups)
          .sort((a, b) => b[1].symbols - a[1].symbols)
          .map(([dir, { files: dirFiles, symbols: dirSymbols }]) => {
            const kinds = dirKindBreakdown[dir] ?? {};
            const kindLabels = Object.entries(kinds)
              .sort((a, b) => b[1] - a[1])
              .slice(0, 5)
              .map(([k, n]) => `${k}: ${n}`)
              .join(", ");
            const dirSlug = dir.replace(/\//g, "-");
            return `
        <a href="files.html#dir-${escapeHtml(dirSlug)}" class="block bg-white shadow rounded-lg border border-gray-200 p-4 hover:border-blue-300 hover:shadow-md transition-all group">
          <div class="flex items-start justify-between">
            <span class="text-lg font-semibold text-gray-900 group-hover:text-blue-600">${escapeHtml(dir)}</span>
            <svg class="h-5 w-5 text-gray-400 group-hover:text-blue-500 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" /></svg>
          </div>
          <dl class="mt-3 space-y-1 text-sm">
            <div class="flex justify-between"><dt class="text-gray-500">Symbols</dt><dd class="font-medium text-gray-900">${dirSymbols}</dd></div>
            <div class="flex justify-between"><dt class="text-gray-500">Files</dt><dd class="font-medium text-gray-900">${dirFiles.length}</dd></div>
          </dl>
          ${kindLabels ? `<p class="mt-2 text-xs text-gray-500 truncate" title="${escapeHtml(kindLabels)}">${escapeHtml(kindLabels)}</p>` : ""}
        </a>`;
          })
          .join("")}
      </div>
      <script>
        (function(){
          var tabGraph = document.getElementById('arch-tab-graph');
          var tabDirs = document.getElementById('arch-tab-dirs');
          var panelGraph = document.getElementById('arch-panel-graph');
          var panelDirs = document.getElementById('arch-panel-dirs');
          if (!tabGraph || !tabDirs || !panelGraph || !panelDirs) return;
          function showGraph() {
            tabGraph.setAttribute('aria-selected', 'true'); tabGraph.classList.add('bg-blue-100', 'text-blue-800', 'border-blue-200'); tabGraph.classList.remove('text-gray-600', 'border-transparent');
            tabDirs.setAttribute('aria-selected', 'false'); tabDirs.classList.remove('bg-blue-100', 'text-blue-800', 'border-blue-200'); tabDirs.classList.add('text-gray-600', 'border-transparent');
            panelGraph.classList.remove('hidden'); panelDirs.classList.add('hidden'); panelDirs.setAttribute('aria-hidden', 'true');
          }
          function showDirs() {
            tabDirs.setAttribute('aria-selected', 'true'); tabDirs.classList.add('bg-blue-100', 'text-blue-800', 'border-blue-200'); tabDirs.classList.remove('text-gray-600', 'border-transparent');
            tabGraph.setAttribute('aria-selected', 'false'); tabGraph.classList.remove('bg-blue-100', 'text-blue-800', 'border-blue-200'); tabGraph.classList.add('text-gray-600', 'border-transparent');
            panelDirs.classList.remove('hidden'); panelGraph.classList.add('hidden'); panelDirs.setAttribute('aria-hidden', 'false');
          }
          tabGraph.addEventListener('click', showGraph);
          tabDirs.addEventListener('click', showDirs);
        })();
      </script>
    </div>

    <div id="top-complex-symbols" class="mb-12">
      <h2 class="text-2xl font-bold text-gray-900 mb-6">Top Complex Symbols</h2>
      <div class="bg-white shadow overflow-x-auto sm:rounded-lg border border-gray-200">
        <table class="min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Name</th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">File</th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Complexity</th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">LOC</th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">
            ${complexSymbols
              .map((s) => {
                const complexity = s.metrics?.cyclomaticComplexity || 0;
                const loc = s.metrics?.linesOfCode || 0;
                return `<tr class="${complexity > 10 ? "bg-red-50" : ""}">
                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-blue-600"><a href="symbols/${s.id}.html" class="hover:underline">${escapeHtml(s.name)}</a></td>
                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500"><a href="files/${fileSlug(s.file)}.html" class="hover:text-blue-600 hover:underline">${escapeHtml(s.file)}</a></td>
                <td class="px-6 py-4 whitespace-nowrap text-sm ${complexity > 10 ? "text-red-600 font-bold" : "text-gray-500"}">${complexity}</td>
                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">${loc}</td>
              </tr>`;
              })
              .join("")}
          </tbody>
        </table>
      </div>
    </div>

    <div class="mb-12">
      <h2 class="text-2xl font-bold text-gray-900 mb-6">Symbol Kinds</h2>
      ${(() => {
        const kindEntries = Object.entries(kindCounts).sort((a, b) => b[1] - a[1]);
        const maxKind = Math.max(1, ...kindEntries.map(([, c]) => c));
        return `
      <div class="space-y-3 max-w-2xl mb-6">
        ${kindEntries
          .map(
            ([kind, count]) => `
        <div class="flex items-center gap-3">
          <span class="text-sm font-medium text-gray-700 w-28 flex-shrink-0">${kind}</span>
          <div class="flex-1 h-6 bg-gray-100 rounded overflow-hidden" title="${count} symbols">
            <div class="h-full bg-blue-500 rounded" style="width:${Math.round((count / maxKind) * 100)}%"></div>
          </div>
          <span class="text-sm font-semibold text-gray-900 w-10 text-right">${count}</span>
        </div>`,
          )
          .join("")}
      </div>
      <div class="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-4">
        ${kindEntries
          .map(
            ([kind, count]) => `
          <div class="bg-white shadow rounded-lg p-4 border border-gray-200 flex justify-between items-center">
            <span class="text-sm font-medium text-gray-500">${kind}</span>
            <span class="text-lg font-semibold text-gray-900">${count}</span>
          </div>`,
          )
          .join("")}
      </div>`;
      })()}
    </div>

    <div class="mb-12">
      <h2 class="text-2xl font-bold text-gray-900 mb-6">Top-Level Symbols</h2>
      <div class="bg-white shadow overflow-x-auto sm:rounded-lg border border-gray-200">
        <table class="min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Name</th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Kind</th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">File</th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">
            ${topLevel
              .sort((a, b) => a.name.localeCompare(b.name))
              .map(
                (s) => `<tr>
                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-blue-600"><a href="symbols/${s.id}.html" class="hover:underline">${escapeHtml(s.name)}</a></td>
                <td class="px-6 py-4 whitespace-nowrap text-sm"><span class="${badgeClass(s.kind)}">${s.kind}</span>${s.deprecated ? ' <span class="px-2 py-0.5 rounded text-xs font-medium border bg-red-50 text-red-700 border-red-200 ml-1 line-through">deprecated</span>' : ""}</td>
                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500"><a href="files/${fileSlug(s.file)}.html" class="hover:text-blue-600 hover:underline">${escapeHtml(s.file)}</a></td>
              </tr>`,
              )
              .join("")}
          </tbody>
        </table>
      </div>
    </div>

    <div class="mb-12">
      <h2 class="text-2xl font-bold text-gray-900 mb-6">Search</h2>
      <div class="flex flex-col md:flex-row gap-6">
        <div class="hidden"></div>
        <div class="flex-1">
           <div class="relative rounded-md shadow-sm mb-4">
            <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
              <span class="text-gray-500 sm:text-sm">🔍</span>
            </div>
            <input type="text" id="search" class="focus:ring-blue-500 focus:border-blue-500 block w-full pl-10 sm:text-sm border-gray-300 rounded-md py-2" placeholder="Search symbols in detail..." aria-label="Search symbols">
          </div>
          <ul id="results" class="bg-white shadow overflow-hidden sm:rounded-md divide-y divide-gray-200" role="region" aria-live="polite" aria-label="Search results"></ul>
        </div>
      </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/fuse.js@6.6.2/dist/fuse.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
    <script>
      mermaid.initialize({startOnLoad:true,theme:'default',securityLevel:'loose',maxTextSize:150000});

      var INDEX = null;
      var FUSE = null;

      function renderResults(results) {
        var r = document.getElementById('results'); r.textContent='';
        if (results.length === 0) {
            r.innerHTML = '<li class="px-4 py-4 text-center text-gray-500 text-sm">No results found</li>';
            return;
        }
        results.slice(0, 100).forEach(function(it){
          var li = document.createElement('li');
          
          var div = document.createElement('div');
          div.className = "px-4 py-4 sm:px-6 hover:bg-gray-50";
          
          var flex = document.createElement('div');
          flex.className = "flex items-center justify-between";
          
          var nameP = document.createElement('p');
          nameP.className = "text-sm font-medium text-blue-600 truncate";
          var a = document.createElement('a'); a.href='symbols/'+it.id+'.html'; a.textContent=it.name; 
          nameP.appendChild(a); 
          
          var badgeDiv = document.createElement('div');
          badgeDiv.className = "ml-2 flex-shrink-0 flex";
          var span = document.createElement('span'); span.className=it.badgeClass; span.textContent=it.kind; 
          badgeDiv.appendChild(span);
          
          flex.appendChild(nameP);
          flex.appendChild(badgeDiv);
          
          var detailsDiv = document.createElement('div');
          detailsDiv.className = "mt-2 sm:flex sm:justify-between";
          
          var leftDetails = document.createElement('div');
          leftDetails.className = "sm:flex";
          
          if (it.signature) { 
             var pSig = document.createElement('p'); pSig.className = "flex items-center text-sm text-gray-500 font-mono bg-gray-50 px-1 rounded truncate max-w-md";
             pSig.textContent = it.signature; 
             leftDetails.appendChild(pSig);
          }
          
          var rightDetails = document.createElement('div');
          rightDetails.className = "mt-2 flex items-center text-sm text-gray-500 sm:mt-0 sm:ml-6";
          
          if (it.file) {
              var pFile = document.createElement('p'); pFile.textContent = it.file;
              rightDetails.appendChild(pFile);
          }
          
          detailsDiv.appendChild(leftDetails);
          detailsDiv.appendChild(rightDetails);
          
          div.appendChild(flex);
          div.appendChild(detailsDiv);
          
          if (it.summary) {
             var pSum = document.createElement('p'); pSum.className="mt-2 text-sm text-gray-600 italic";
             pSum.textContent = it.summary;
             div.appendChild(pSum);
          }

          li.appendChild(div);
          r.appendChild(li);
        });
      }

      function doSearch(q) {
        if (!INDEX) return;
        var results = [];
        if (q && q.trim().length>0 && FUSE) {
          results = FUSE.search(q).map(function(r){ return r.item; });
        } else {
          results = INDEX.items.slice();
        }
        renderResults(results);
      }

      fetch('search.json')
        .then(function (r) { return r.json(); })
        .then(function (data) {
          if (Array.isArray(data)) {
            INDEX = { items: data };
          } else {
            INDEX = data;
          }

          try {
            FUSE = new Fuse(INDEX.items, { keys: [{ name: 'name', weight: 0.6 }, { name: 'signature', weight: 0.2 }, { name: 'summary', weight: 0.2 }], includeMatches: true, threshold: 0.35 });
          } catch (e) { console.warn('Fuse init failed', e); FUSE = null; }
          document.getElementById('search').addEventListener('input', function (e) { doSearch(e.target.value); });
        });
    </script>
  `;

  // No filters in sidebar for dashboard
  return layout("Dashboard", "index.html", body);
}

export function renderFilesPage(files: string[], symbols: CodeSymbol[]): string {
  // 1. Build the tree
  interface TreeNode {
    name: string;
    path: string; // full path so far
    isFile: boolean;
    children: Record<string, TreeNode>;
    symbolCount: number;
  }

  const root: TreeNode = {
    name: "root",
    path: "",
    isFile: false,
    children: {},
    symbolCount: 0,
  };

  const symbolCounts = new Map<string, number>();
  for (const s of symbols) {
    symbolCounts.set(s.file, (symbolCounts.get(s.file) ?? 0) + 1);
  }

  for (const file of files) {
    const parts = file.split("/");
    let current = root;
    let currentPath = "";

    for (let i = 0; i < parts.length; i++) {
      const part = parts[i];
      const isLast = i === parts.length - 1;
      currentPath = currentPath ? `${currentPath}/${part}` : part;

      if (!current.children[part]) {
        current.children[part] = {
          name: part,
          path: currentPath,
          isFile: isLast,
          children: {},
          symbolCount: 0,
        };
      }
      current = current.children[part];
    }
    // Set symbol count for the file node
    current.symbolCount = symbolCounts.get(file) ?? 0;
  }

  // 2. Propagate counts up
  function calculateCounts(node: TreeNode): number {
    if (node.isFile) return node.symbolCount;
    let sum = 0;
    for (const child of Object.values(node.children)) {
      sum += calculateCounts(child);
    }
    node.symbolCount = sum;
    return sum;
  }
  calculateCounts(root);

  // 3. Recursive Render
  function renderNode(node: TreeNode, depth: number): string {
    const indent = depth * 0.75; // rem — compact so deep paths don't use too much horizontal space
    const children = Object.values(node.children).sort((a, b) => {
      // Directories first, then alphabetical
      if (a.isFile !== b.isFile) return a.isFile ? 1 : -1;
      return a.name.localeCompare(b.name);
    });

    if (node.isFile) {
      return `
        <div class="file-tree-row flex items-center py-1 hover:bg-gray-50 group transition-colors rounded-md px-2 -mx-2" data-path="${escapeHtml(node.path)}" data-name="${escapeHtml(node.name)}">
          <div style="width: ${indent}rem" class="flex-shrink-0"></div>
          <svg class="h-4 w-4 text-gray-400 mr-2 flex-shrink-0 group-hover:text-blue-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
          </svg>
          <a href="files/${fileSlug(node.path)}.html" class="text-sm text-gray-700 hover:text-blue-600 font-medium truncate flex-1 block">
            ${escapeHtml(node.name)}
          </a>
          <span class="text-xs text-gray-400 ml-2 bg-gray-100 px-2 py-0.5 rounded-full border border-gray-200">${node.symbolCount}</span>
        </div>
      `;
    } else {
      // Directory
      const inner = children.map((c) => renderNode(c, depth + 1)).join("");
      // Don't render root wrapper if it's the top-level container call
      if (node.name === "root") return inner;

      const dirId = "dir-" + node.path.replace(/\//g, "-");
      return `
        <details class="group/folder file-tree-dir" open id="${escapeHtml(dirId)}" data-path="${escapeHtml(node.path)}" data-name="${escapeHtml(node.name)}">
          <summary class="flex items-center py-1 hover:bg-gray-50 cursor-pointer select-none rounded-md px-2 -mx-2 transition-colors">
            <div style="width: ${indent}rem" class="flex-shrink-0"></div>
            <svg class="h-4 w-4 text-gray-400 mr-2 flex-shrink-0 group-open/folder:hidden" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 7v10a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-6l-2-2H5a2 2 0 00-2 2z" />
            </svg>
            <svg class="h-4 w-4 text-blue-500 mr-2 flex-shrink-0 hidden group-open/folder:block" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 19a2 2 0 01-2-2V7a2 2 0 012-2h4l2 2h4a2 2 0 012 2v1M5 19h14a2 2 0 002-2v-5a2 2 0 00-2-2H9a2 2 0 00-2 2l-2 2z" />
            </svg>
            <span class="text-sm font-semibold text-gray-800 flex-1 truncate">${escapeHtml(node.name)}</span>
            <span class="text-xs text-gray-400 ml-2">${node.symbolCount}</span>
          </summary>
          <div class="border-l border-gray-100 ml-2 pl-1 my-1">
            ${inner}
          </div>
        </details>
      `;
    }
  }

  const body = `
    <div class="flex flex-wrap items-center justify-between gap-4 mb-6 pb-4 border-b border-gray-200">
      <h1 class="text-3xl font-bold text-gray-900">File Explorer</h1>
      <div class="text-sm text-gray-500">
        <span class="font-semibold text-gray-900">${files.length}</span> files,
        <span class="font-semibold text-gray-900">${symbols.length}</span> symbols
      </div>
    </div>

    <div class="mb-4">
      <label for="file-tree-filter" class="block text-sm font-medium text-gray-700 mb-1">Filter by path or name</label>
      <input type="text" id="file-tree-filter" class="block w-full rounded-md border-gray-300 shadow-sm focus:ring-blue-500 focus:border-blue-500 sm:text-sm py-2 px-3" placeholder="e.g. src/site or .ts" aria-label="Filter file tree">
    </div>

    <div class="bg-white shadow rounded-lg border border-gray-200 overflow-hidden">
      <div class="p-4 bg-gray-50 border-b border-gray-200 flex flex-wrap justify-between items-center gap-2">
        <span class="text-xs font-semibold text-gray-500 uppercase tracking-wider">Project Source</span>
        <div class="flex gap-2">
          <button type="button" id="file-tree-expand-all" class="text-xs text-blue-600 hover:text-blue-800 font-medium">Expand All</button>
          <button type="button" onclick="document.querySelectorAll('.file-tree-dir').forEach(d => d.open = false)" class="text-xs text-blue-600 hover:text-blue-800 font-medium">Collapse All</button>
        </div>
      </div>
      <div class="p-2 overflow-x-auto" id="file-tree-container">
        ${renderNode(root, 0)}
      </div>
    </div>

    <script>
      (function(){
        var filterInput = document.getElementById('file-tree-filter');
        var container = document.getElementById('file-tree-container');
        var expandBtn = document.getElementById('file-tree-expand-all');
        if (!filterInput || !container) return;

        function filterTree() {
          var q = (filterInput.value || '').trim().toLowerCase();
          var dirs = container.querySelectorAll('.file-tree-dir');
          var rows = container.querySelectorAll('.file-tree-row');
          function match(el) {
            var path = (el.getAttribute('data-path') || '').toLowerCase();
            var name = (el.getAttribute('data-name') || '').toLowerCase();
            return !q || path.indexOf(q) !== -1 || name.indexOf(q) !== -1;
          }
          rows.forEach(function(el) { el.style.display = match(el) ? '' : 'none'; });
          dirs.forEach(function(el) { el.style.display = match(el) ? '' : 'none'; });
          if (q) {
            [].slice.call(dirs).reverse().forEach(function(d) {
              var inside = d.querySelectorAll('.file-tree-dir, .file-tree-row');
              var anyVisible = [].some.call(inside, function(c) { return c.style.display !== 'none'; });
              if (anyVisible) d.style.display = '';
            });
            dirs.forEach(function(d) { if (d.style.display !== 'none') d.setAttribute('open', ''); });
          }
        }

        filterInput.addEventListener('input', filterTree);
        filterInput.addEventListener('keydown', function(e) { if (e.key === 'Escape') { filterInput.value = ''; filterTree(); filterInput.blur(); } });
        if (expandBtn) expandBtn.addEventListener('click', function() { container.querySelectorAll('.file-tree-dir').forEach(function(d) { d.setAttribute('open', ''); }); });
      })();
    </script>
  `;

  return layout("Files", "files.html", body);
}

export interface ArchViolationRow {
  rule: string;
  file: string;
  symbol_id: string | null;
  message: string;
  severity: string;
}

export function renderSymbolPage(
  symbol: CodeSymbol,
  allSymbols: CodeSymbol[],
  relationships: RelationshipRow[],
  sourceCode?: string,
  archViolationsForSymbol: ArchViolationRow[] = [],
): string {
  const children = allSymbols.filter((s) => s.parent === symbol.id);
  const outgoing = relationships.filter((r) => r.source_id === symbol.id);
  const incoming = relationships.filter((r) => r.target_id === symbol.id);

  let sourceSnippet = "";
  if (sourceCode) {
    const lines = sourceCode.split("\n");
    const start = Math.max(0, symbol.startLine - 1);
    const end = Math.min(lines.length, symbol.endLine);
    sourceSnippet = lines.slice(start, end).join("\n");
  }

  const breadcrumb = [
    '<a href="../index.html" class="hover:text-gray-700">Dashboard</a>',
    `<a href="../files/${fileSlug(symbol.file)}.html" class="hover:text-gray-700">${escapeHtml(symbol.file)}</a>`,
  ];
  if (symbol.parent) {
    const parent = allSymbols.find((s) => s.id === symbol.parent);
    if (parent) {
      breadcrumb.splice(1, 0, `<a href="${parent.id}.html" class="hover:text-gray-700">${escapeHtml(parent.name)}</a>`);
    }
  }
  breadcrumb.push(`<span class="text-gray-900 font-semibold">${escapeHtml(symbol.name)}</span>`);

  const depGraph = buildMermaidForSymbol(symbol, allSymbols, relationships, "outgoing", true);
  const impactGraph = buildMermaidForSymbol(symbol, allSymbols, relationships, "incoming", true);

  const body = `
    <nav class="flex mb-6" aria-label="Breadcrumb">
      <ol class="flex items-center space-x-2 text-sm text-gray-500">
        ${breadcrumb.map((item, i) => `
          <li>
            <div class="flex items-center">
              ${i > 0 ? '<svg class="flex-shrink-0 h-5 w-5 text-gray-300 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"><path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd" /></svg>' : ''}
              ${item}
            </div>
          </li>
        `).join("")}
      </ol>
    </nav>

    <div class="bg-white shadow rounded-lg mb-8 border border-gray-200">
      <div class="px-6 py-5 border-b border-gray-200 flex items-center justify-between flex-wrap gap-4">
        <h1 class="text-2xl font-bold text-gray-900 flex items-center flex-wrap gap-2">
           <span class="mr-2">${escapeHtml(symbol.name)}</span>
           <span class="${badgeClass(symbol.kind)}">${symbol.kind}</span>
           ${visibilityBadge(symbol.visibility)}
           ${layerBadge(symbol.layer)}
           ${statusBadges(symbol)}
           ${violationsBadges(symbol, "../governance.html")}
        </h1>
        <div class="text-sm text-gray-500">
          Last updated: ${escapeHtml(formatDate(symbol.lastModified) ?? "Unknown")}
        </div>
      </div>
      <div class="px-6 py-5 space-y-4">
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <h3 class="text-sm font-medium text-gray-500">Location</h3>
            <p class="mt-1 text-sm text-gray-900"><a href="../files/${fileSlug(symbol.file)}.html" class="text-blue-600 hover:underline">${escapeHtml(symbol.file)}</a>:${symbol.startLine}-${symbol.endLine}</p>
          </div>
          ${symbol.metrics ? `
          <div>
            <h3 class="text-sm font-medium text-gray-500">Metrics</h3>
            <div class="mt-1 flex space-x-4 text-sm text-gray-900">
              <span>LOC: ${symbol.metrics.linesOfCode ?? "-"}</span>
              <span>Complexity: <span class="${(symbol.metrics.cyclomaticComplexity ?? 0) > 10 ? 'text-red-600 font-bold' : ''}">${symbol.metrics.cyclomaticComplexity ?? "-"}</span></span>
              <span>Params: ${symbol.metrics.parameterCount ?? "-"}</span>
            </div>
          </div>` : ""}
        </div>

        ${symbol.signature ? `
        <div>
          <h3 class="text-sm font-medium text-gray-500">Signature</h3>
          <div class="mt-1 bg-gray-50 rounded-md p-3 font-mono text-sm text-gray-800 border border-gray-200 overflow-x-auto">
            ${escapeHtml(symbol.signature)}
          </div>
        </div>` : ""}

        ${symbol.pattern ? `
        <div>
          <h3 class="text-sm font-medium text-gray-500">Pattern</h3>
          <p class="mt-1 text-sm text-gray-900 bg-green-50 text-green-700 px-2 py-1 rounded inline-block border border-green-200">${escapeHtml(symbol.pattern)}</p>
        </div>` : ""}

        ${symbol.docRef ? `
        <div>
          <h3 class="text-sm font-medium text-gray-500">Documentation</h3>
          <p class="mt-1 text-sm"><a href="../${escapeHtml(symbol.docRef.replace(/\.md$/, ".html"))}" class="text-blue-600 hover:underline flex items-center"><svg class="h-4 w-4 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg>${escapeHtml(symbol.docRef)}</a></p>
        </div>` : ""}
        
        ${symbol.summary ? `
        <div class="prose prose-sm max-w-none text-gray-700">
           <h3 class="text-sm font-medium text-gray-500 mb-1">Summary</h3>
           <p>${escapeHtml(symbol.summary)}</p>
        </div>` : ""}

        ${symbol.violations?.length
    ? `
        <div>
          <h3 class="text-sm font-medium text-gray-500 mb-2">Code quality</h3>
          <p class="text-sm text-gray-600 mb-2">This symbol has governance findings. <a href="../governance.html#reaper" class="text-blue-600 hover:underline">View all</a>.</p>
          <div class="flex flex-wrap gap-2">
            ${symbol.violations.map((v) => `<span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-amber-100 text-amber-800 border border-amber-200">${escapeHtml(v)}</span>`).join("")}
          </div>
        </div>`
    : ""}

        ${archViolationsForSymbol.length > 0
    ? `
        <div>
          <h3 class="text-sm font-medium text-gray-500 mb-2">Architecture violations</h3>
          <p class="text-sm text-gray-600 mb-2"><a href="../governance.html#arch" class="text-blue-600 hover:underline">View all</a></p>
          <ul class="list-disc list-inside space-y-1 text-sm text-gray-700">
            ${archViolationsForSymbol.map((v) => `<li><span class="font-medium ${v.severity === "error" ? "text-red-600" : "text-amber-700"}">[${escapeHtml(v.severity)}]</span> ${escapeHtml(v.rule)}: ${escapeHtml(v.message)}</li>`).join("")}
          </ul>
        </div>`
    : ""}

        ${symbol.tags ? `
        <div>
          <h3 class="text-sm font-medium text-gray-500 mb-2">Tags</h3>
          <div class="flex flex-wrap gap-2">
            ${symbol.tags.map((t) => `<span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-gray-100 text-gray-800 border border-gray-200">#${escapeHtml(t)}</span>`).join("")}
          </div>
        </div>` : ""}
      </div>
    </div>

    ${sourceSnippet
      ? `<div class="mb-12">
            <h2 class="text-xl font-bold text-gray-900 mb-4">Source Code</h2>
            <div class="rounded-lg overflow-hidden border border-gray-200">
              <pre class="bg-gray-50 p-4 overflow-x-auto text-sm font-mono leading-tight"><code class="language-typescript">${escapeCodeBlocks(sourceSnippet)}</code></pre>
            </div>
           </div>
           <script>hljs.highlightAll();</script>`
      : ""}

    ${children.length > 0
      ? `<div class="mb-12">
            <h2 class="text-xl font-bold text-gray-900 mb-4">Members</h2>
            <div class="bg-white shadow overflow-x-auto sm:rounded-lg border border-gray-200">
              <table class="min-w-full divide-y divide-gray-200">
                <thead class="bg-gray-50">
                  <tr>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Name</th>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Kind</th>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Visibility</th>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Status</th>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Signature</th>
                  </tr>
                </thead>
                <tbody class="bg-white divide-y divide-gray-200">
                  ${children
                    .map(
                      (c) => `<tr>
                    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-blue-600"><a href="${c.id}.html" class="hover:underline">${escapeHtml(c.name)}</a></td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm"><span class="${badgeClass(c.kind)}">${c.kind}</span></td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm">${visibilityBadge(c.visibility)}</td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm">${statusBadges(c)}${violationsBadges(c, "../governance.html") || "-"}</td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm font-mono text-gray-500 text-xs">${c.signature ? escapeHtml(c.signature) : "-"}</td>
                  </tr>`,
                    )
                    .join("")}
                </tbody>
              </table>
            </div>
          </div>`
      : ""}

    ${(() => {
      const listeners = incoming.filter((r) => r.type === "listens_to");
      if (symbol.kind === "event" && listeners.length > 0) {
        return `<div class="mb-12">
            <h2 class="text-xl font-bold text-gray-900 mb-4">Listeners</h2>
            <div class="bg-white shadow overflow-x-auto sm:rounded-lg border border-gray-200">
              <table class="min-w-full divide-y divide-gray-200">
                <thead class="bg-gray-50">
                  <tr>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Listener</th>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">File</th>
                  </tr>
                </thead>
                <tbody class="bg-white divide-y divide-gray-200">
                  ${listeners
                    .map((r) => {
                      const source = allSymbols.find((s) => s.id === r.source_id);
                      return `<tr>
                    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-blue-600">${source ? `<a href="${source.id}.html" class="hover:underline">${escapeHtml(source.name)}</a>` : r.source_id}</td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">${source ? `<a href="../files/${fileSlug(source.file)}.html" class="hover:underline hover:text-blue-600">${escapeHtml(source.file)}</a>` : "-"}</td>
                  </tr>`;
                    })
                    .join("")}
                </tbody>
              </table>
            </div>
          </div>`;
      }
      return "";
    })()}

    <div class="grid grid-cols-1 xl:grid-cols-2 gap-8">
       <div>
          ${depGraph
            ? `<div class="mb-8">
                  <h2 class="text-xl font-bold text-gray-900 mb-4">Dependencies (Outgoing)</h2>
                  <div class="bg-white shadow rounded-lg p-4 border border-gray-200 overflow-x-auto">
                    <div class="mermaid">${depGraph}</div>
                  </div>
                </div>`
            : ""}
          
          ${outgoing.length > 0
            ? `<div class="bg-white shadow overflow-x-auto sm:rounded-lg border border-gray-200 mb-8">
                <table class="min-w-full divide-y divide-gray-200">
                  <thead class="bg-gray-50">
                    <tr><th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Target</th><th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Type</th></tr>
                  </thead>
                  <tbody class="bg-white divide-y divide-gray-200">
                    ${outgoing
                      .map((r) => {
                        const target = allSymbols.find((s) => s.id === r.target_id);
                        return `<tr>
                      <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-blue-600">${target ? `<a href="${target.id}.html" class="hover:underline">${escapeHtml(target.name)}</a>` : r.target_id}</td>
                      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">${r.type}</td>
                    </tr>`;
                      })
                      .join("")}
                  </tbody>
                </table>
              </div>`
            : "<p class='text-gray-500 italic mb-8'>No outgoing dependencies.</p>"}
       </div>
       
       <div>
          ${impactGraph
            ? `<div class="mb-8">
                  <h2 class="text-xl font-bold text-gray-900 mb-4">Impact (Incoming)</h2>
                  <div class="bg-white shadow rounded-lg p-4 border border-gray-200 overflow-x-auto">
                    <div class="mermaid">${impactGraph}</div>
                  </div>
                </div>`
            : ""}
          
          ${incoming.length > 0
            ? `<div class="bg-white shadow overflow-x-auto sm:rounded-lg border border-gray-200 mb-8">
                <table class="min-w-full divide-y divide-gray-200">
                  <thead class="bg-gray-50">
                    <tr><th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Source</th><th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Type</th></tr>
                  </thead>
                  <tbody class="bg-white divide-y divide-gray-200">
                    ${incoming
                      .map((r) => {
                        const source = allSymbols.find((s) => s.id === r.source_id);
                        return `<tr>
                      <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-blue-600">${source ? `<a href="${source.id}.html" class="hover:underline">${escapeHtml(source.name)}</a>` : r.source_id}</td>
                      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">${r.type}</td>
                    </tr>`;
                      })
                      .join("")}
                  </tbody>
                </table>
              </div>`
            : "<p class='text-gray-500 italic mb-8'>No incoming dependencies.</p>"}
       </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
    <script>mermaid.initialize({startOnLoad:true,theme:'default',securityLevel:'loose',maxTextSize:150000});</script>
  `;

  return layout(symbol.name, "", body, 1);
}

const GHOST_SYMBOL_NAMES = new Set(["class", "interface", "enum", "trait", "function", "type", "struct", "abstract"]);

export function renderFilePage(
  filePath: string,
  symbols: CodeSymbol[],
  sourceCode?: string,
  relationships?: RelationshipRow[],
  allSymbols?: CodeSymbol[],
  archViolationsForFile: ArchViolationRow[] = [],
): string {
  const displaySymbols = symbols.filter((s) => !GHOST_SYMBOL_NAMES.has(s.name));
  const topLevel = displaySymbols.filter((s) => !s.parent);

  const totalSymbols = displaySymbols.length;
  const totalLOC = sourceCode ? sourceCode.split("\n").length : 0;
  const avgComplexity =
    displaySymbols.length > 0
      ? displaySymbols
          .filter((s) => s.metrics?.cyclomaticComplexity)
          .reduce((sum, s) => sum + (s.metrics!.cyclomaticComplexity || 0), 0) / displaySymbols.length
      : 0;

  const kindCounts: Record<string, number> = {};
  for (const s of displaySymbols) {
    kindCounts[s.kind] = (kindCounts[s.kind] ?? 0) + 1;
  }

  let fileGraph = "";
  if (relationships && allSymbols) {
    fileGraph = buildMermaidForFile(filePath, allSymbols, relationships, true);
  }

  const body = `
    <nav class="flex mb-6" aria-label="Breadcrumb">
       <ol class="flex items-center space-x-2 text-sm text-gray-500">
         <li><a href="../index.html" class="hover:text-gray-700">Dashboard</a></li>
         <li><svg class="flex-shrink-0 h-5 w-5 text-gray-300" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"><path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd" /></svg></li>
         <li><span class="text-gray-900 font-semibold">${escapeHtml(filePath)}</span></li>
       </ol>
    </nav>
  
    <h1 class="text-2xl font-bold text-gray-900 mb-6 flex items-center">
      <svg class="h-8 w-8 text-gray-400 mr-3" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg>
      ${escapeHtml(filePath)}
    </h1>

    <div class="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
      <div class="bg-white overflow-hidden shadow rounded-lg border border-gray-200 p-4 text-center">
        <dt class="text-sm font-medium text-gray-500 truncate">Total Symbols</dt>
        <dd class="mt-1 text-2xl font-semibold text-gray-900">${totalSymbols}</dd>
      </div>
      <div class="bg-white overflow-hidden shadow rounded-lg border border-gray-200 p-4 text-center">
        <dt class="text-sm font-medium text-gray-500 truncate">Lines of Code</dt>
        <dd class="mt-1 text-2xl font-semibold text-gray-900">${totalLOC}</dd>
      </div>
      <div class="bg-white overflow-hidden shadow rounded-lg border border-gray-200 p-4 text-center">
        <dt class="text-sm font-medium text-gray-500 truncate">Avg Complexity</dt>
        <dd class="mt-1 text-2xl font-semibold text-gray-900">${avgComplexity.toFixed(1)}</dd>
      </div>
      <div class="bg-white overflow-hidden shadow rounded-lg border border-gray-200 p-4 text-center">
        <dt class="text-sm font-medium text-gray-500 truncate">Symbol Types</dt>
        <dd class="mt-1 text-2xl font-semibold text-gray-900">${Object.keys(kindCounts).length}</dd>
      </div>
    </div>

    ${fileGraph
      ? `
    <div class="mb-12">
      <h2 class="text-xl font-bold text-gray-900 mb-4">File Relationships</h2>
      <div class="bg-white shadow rounded-lg p-6 border border-gray-200 overflow-x-auto">
        <div class="mermaid">${fileGraph}</div>
      </div>
    </div>`
      : ""}

    ${archViolationsForFile.length > 0
      ? `
    <div class="mb-12">
      <h2 class="text-xl font-bold text-gray-900 mb-4">Architecture violations</h2>
      <p class="text-sm text-gray-600 mb-4"><a href="../governance.html#arch" class="text-blue-600 hover:underline">View all</a></p>
      <ul class="list-disc list-inside space-y-1 text-sm text-gray-700">
        ${archViolationsForFile.map((v) => `<li><span class="font-medium ${v.severity === "error" ? "text-red-600" : "text-amber-700"}">[${escapeHtml(v.severity)}]</span> ${escapeHtml(v.rule)}: ${escapeHtml(v.message)}</li>`).join("")}
      </ul>
    </div>`
      : ""}

    <div class="mb-12">
      <h2 class="text-xl font-bold text-gray-900 mb-4">Symbols by Kind</h2>
      <div class="flex flex-wrap gap-4">
        ${Object.entries(kindCounts)
          .sort((a, b) => b[1] - a[1])
          .map(
            ([kind, count]) => `
          <div class="bg-white shadow rounded-lg px-4 py-2 border border-gray-200 flex items-center space-x-2">
            <span class="${badgeClass(kind)}">${kind}</span>
            <span class="text-gray-900 font-semibold">${count}</span>
          </div>`,
          )
          .join("")}
      </div>
    </div>

    <div class="mb-12">
      <h2 class="text-xl font-bold text-gray-900 mb-4">All Symbols</h2>
      <div class="bg-white shadow overflow-x-auto sm:rounded-lg border border-gray-200">
        <table class="min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Name</th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Kind</th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Visibility</th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Status</th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Lines</th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Signature</th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">
            ${topLevel
              .sort((a, b) => a.startLine - b.startLine)
              .map((s) => {
                const children = displaySymbols.filter((c) => c.parent === s.id);
                return `<tr>
              <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-blue-600"><a href="../symbols/${s.id}.html" class="hover:underline">${escapeHtml(s.name)}</a></td>
              <td class="px-6 py-4 whitespace-nowrap text-sm"><span class="${badgeClass(s.kind)}">${s.kind}</span></td>
              <td class="px-6 py-4 whitespace-nowrap text-sm">${visibilityBadge(s.visibility)}</td>
              <td class="px-6 py-4 whitespace-nowrap text-sm">${statusBadges(s)}${violationsBadges(s, "../governance.html") || "-"}</td>
              <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">${s.startLine}-${s.endLine}</td>
              <td class="px-6 py-4 whitespace-nowrap text-sm font-mono text-gray-500 text-xs">${s.signature ? `<code>${escapeHtml(s.signature)}</code>` : "-"}</td>
            </tr>
            ${children
              .map(
                (c) => `<tr>
              <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-blue-600 pl-12 border-l-4 border-gray-100"><a href="../symbols/${c.id}.html" class="hover:underline">${escapeHtml(c.name)}</a></td>
              <td class="px-6 py-4 whitespace-nowrap text-sm"><span class="${badgeClass(c.kind)}">${c.kind}</span></td>
              <td class="px-6 py-4 whitespace-nowrap text-sm">${visibilityBadge(c.visibility)}</td>
              <td class="px-6 py-4 whitespace-nowrap text-sm">${statusBadges(c)}${violationsBadges(c, "../governance.html") || "-"}</td>
              <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">${c.startLine}-${c.endLine}</td>
              <td class="px-6 py-4 whitespace-nowrap text-sm font-mono text-gray-500 text-xs">${c.signature ? `<code>${escapeHtml(c.signature)}</code>` : "-"}</td>
            </tr>`,
              )
              .join("")}`;
              })
              .join("")}
          </tbody>
        </table>
      </div>
    </div>

    ${sourceCode
      ? `<div class="mb-12">
            <h2 class="text-xl font-bold text-gray-900 mb-4">Full Source</h2>
            <div class="rounded-lg overflow-hidden border border-gray-200">
              <pre class="bg-gray-50 p-4 overflow-x-auto text-sm font-mono leading-tight"><code class="language-typescript">${escapeCodeBlocks(sourceCode)}</code></pre>
            </div>
           </div>
           <script>hljs.highlightAll();</script>`
      : ""}

    <script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
    <script>mermaid.initialize({startOnLoad:true,theme:'default',securityLevel:'loose',maxTextSize:150000});</script>
  `;

  return layout(filePath, "", body, 1);
}

export function renderRelationshipsPage(
  relationships: RelationshipRow[],
  symbols: CodeSymbol[],
): string {
  const symbolMap = new Map(symbols.map((s) => [s.id, s]));

  const byType: Record<string, number> = {};
  for (const r of relationships) {
    byType[r.type] = (byType[r.type] ?? 0) + 1;
  }

  const topConnectedGraph = buildMermaidTopConnected(symbols, relationships, 30, true);

  const body = `
    <h1 class="text-3xl font-bold text-gray-900 mb-8 pb-4 border-b border-gray-200">Relationships</h1>

    <div class="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-4 mb-8">
      ${Object.entries(byType)
        .sort((a, b) => b[1] - a[1])
        .map(
          ([type, count]) => `
        <button onclick="filterByType('${type}')" class="bg-white shadow rounded-lg p-4 border border-gray-200 text-center hover:bg-blue-50 transition-colors focus:outline-none focus:ring-2 focus:ring-blue-500">
          <div class="text-2xl font-bold text-blue-600">${count}</div>
          <div class="text-xs font-medium text-gray-500 uppercase tracking-wide mt-1">${type}</div>
        </button>`,
        )
        .join("")}
    </div>

    ${topConnectedGraph
      ? `
    <div class="mb-12">
      <h2 class="text-xl font-bold text-gray-900 mb-4">Architecture Overview (Top 30 Connected)</h2>
      <div class="bg-white shadow rounded-lg p-6 border border-gray-200 overflow-x-auto">
        <div class="mermaid">${topConnectedGraph}</div>
      </div>
    </div>`
      : ""}

    <div class="mb-8 p-4 bg-blue-50 rounded-md border border-blue-100 text-blue-800 text-sm">
       Each symbol page contains focused dependency and impact graphs. Below is the full relationship table.
       Click a statistic card above or type below to filter.
    </div>

    <div class="mb-6">
      <label for="relationship-filter" class="block text-sm font-medium text-gray-700 mb-2">Filter Relationships</label>
      <input type="text" id="relationship-filter" class="shadow-sm focus:ring-blue-500 focus:border-blue-500 block w-full sm:text-sm border-gray-300 rounded-md p-2" placeholder="Type to filter by source, target or type...">
    </div>

    <div class="bg-white shadow overflow-x-auto sm:rounded-lg border border-gray-200">
      <table class="min-w-full divide-y divide-gray-200" id="relationships-table">
        <thead class="bg-gray-50">
          <tr>
             <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Source</th>
             <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Type</th>
             <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Target</th>
          </tr>
        </thead>
        <tbody class="bg-white divide-y divide-gray-200">
          ${relationships
            .map((r) => {
              const source = symbolMap.get(r.source_id);
              const target = symbolMap.get(r.target_id);
              return `<tr data-source="${escapeHtml(source?.name || r.source_id)}" data-type="${r.type}" data-target="${escapeHtml(target?.name || r.target_id)}">
            <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-blue-600">${source ? `<a href="symbols/${source.id}.html" class="hover:underline">${escapeHtml(source.name)}</a>` : r.source_id}</td>
            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500"><span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-gray-100 text-gray-800">${r.type}</span></td>
            <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-blue-600">${target ? `<a href="symbols/${target.id}.html" class="hover:underline">${escapeHtml(target.name)}</a>` : r.target_id}</td>
          </tr>`;
            })
            .join("")}
        </tbody>
      </table>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
    <script>
      mermaid.initialize({startOnLoad:true,theme:'default',securityLevel:'loose',maxTextSize:150000});

      const filterInput = document.getElementById('relationship-filter');
      const tableRows = document.querySelectorAll('#relationships-table tbody tr');

      function filterTable(filterValue) {
        const filter = filterValue.toLowerCase();
        tableRows.forEach(row => {
          const source = row.dataset.source.toLowerCase();
          const type = row.dataset.type.toLowerCase();
          const target = row.dataset.target.toLowerCase();

          const matches = source.includes(filter) || type.includes(filter) || target.includes(filter);
          row.style.display = matches ? '' : 'none';
        });
      }

      function filterByType(type) {
        filterInput.value = type;
        filterTable(type);
      }

      filterInput.addEventListener('input', function(e) {
        filterTable(e.target.value);
      });
    </script>
  `;

  return layout("Relationships", "relationships.html", body);
}

export function renderPatternsPage(patterns: DetectedPattern[], symbols: CodeSymbol[]): string {
  const symbolMap = new Map(symbols.map((s) => [s.id, s]));

  const body = `
    <h1 class="text-3xl font-bold text-gray-900 mb-8 pb-4 border-b border-gray-200">Detected Patterns</h1>

    ${patterns.length === 0
      ? "<div class='text-center py-12 text-gray-500'>No patterns detected.</div>"
      : `<div class="grid grid-cols-1 gap-6">
            ${patterns
              .map(
                (p) => `
          <div class="bg-white shadow rounded-lg border border-gray-200 overflow-hidden">
            <div class="px-6 py-4 border-b border-gray-200 bg-gray-50 flex justify-between items-center">
               <h3 class="text-lg font-medium text-gray-900">${escapeHtml(p.kind)}</h3>
               <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${p.confidence > 0.8 ? 'bg-green-100 text-green-800' : 'bg-yellow-100 text-yellow-800'}">
                 Confidence: ${(p.confidence * 100).toFixed(0)}%
               </span>
            </div>
            <div class="p-6">
              <div class="mb-4">
                <span class="text-sm font-medium text-gray-500 uppercase tracking-wider block mb-2">Symbols Involved</span>
                <div class="flex flex-wrap gap-2">
                   ${p.symbols
                     .map((id) => {
                       const s = symbolMap.get(id);
                       return s ? `<a href="symbols/${s.id}.html" class="inline-flex items-center px-3 py-1 rounded-md text-sm font-medium bg-blue-50 text-blue-700 hover:bg-blue-100 transition-colors">${escapeHtml(s.name)}</a>` : `<span class="text-gray-500">${id}</span>`;
                     })
                     .join("")}
                </div>
              </div>
              
              ${p.violations.length > 0
                ? `<div>
                      <span class="text-sm font-medium text-red-500 uppercase tracking-wider block mb-2">Violations</span>
                      <ul class="list-disc pl-5 space-y-1 text-sm text-gray-700">
                        ${p.violations.map((v) => `<li>${escapeHtml(v)}</li>`).join("")}
                      </ul>
                    </div>`
                : "<p class='text-sm text-green-600 flex items-center'><svg class='h-4 w-4 mr-1' fill='none' viewBox='0 0 24 24' stroke='currentColor'><path stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='M5 13l4 4L19 7'/></svg> No violations found</p>"
              }
            </div>
          </div>`,
              )
              .join("")}
          </div>`
    }
  `;

  return layout("Patterns", "patterns.html", body);
}

export function renderDocsPage(docRefs: string[]): string {
  const sorted = [...docRefs].sort();
  const body = `
    <h1 class="text-3xl font-bold text-gray-900 mb-8 pb-4 border-b border-gray-200">Documentation</h1>
    <p class="text-gray-600 mb-6">Markdown docs referenced by symbols. Open the HTML version to read in the site.</p>
    ${sorted.length === 0
      ? "<div class='text-center py-12 text-gray-500'>No doc references yet. Add doc_ref to symbols or link docs in frontmatter.</div>"
      : `
    <div class="bg-white shadow overflow-x-auto sm:rounded-lg border border-gray-200">
      <ul class="divide-y divide-gray-200">
        ${sorted
          .map(
            (ref) => {
              const htmlRef = ref.replace(/\.md$/i, ".html");
              const name = ref.split("/").pop() || ref;
              return `<li class="px-6 py-4"><a href="${escapeHtml(htmlRef)}" class="text-blue-600 hover:underline font-medium">${escapeHtml(name)}</a><span class="text-gray-400 text-sm ml-2">${escapeHtml(ref)}</span></li>`;
            },
          )
          .join("")}
      </ul>
    </div>`}
  `;

  return layout("Docs", "docs.html", body);
}

export function renderDeprecatedPage(symbols: CodeSymbol[]): string {
  const deprecated = symbols.filter((s) => s.deprecated).sort((a, b) => a.name.localeCompare(b.name));

  const body = `
    <h1 class="text-3xl font-bold text-gray-900 mb-8 pb-4 border-b border-gray-200">Deprecated Symbols</h1>
    <p class="text-gray-600 mb-6">Symbols marked as deprecated. Consider migrating callers before removal.</p>
    ${deprecated.length === 0
      ? "<div class='text-center py-12 text-gray-500'>No deprecated symbols.</div>"
      : `
    <div class="bg-white shadow overflow-x-auto sm:rounded-lg border border-gray-200">
      <table class="min-w-full divide-y divide-gray-200">
        <thead class="bg-gray-50">
          <tr>
            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Name</th>
            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Kind</th>
            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">File</th>
            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Signature</th>
          </tr>
        </thead>
        <tbody class="bg-white divide-y divide-gray-200">
          ${deprecated
            .map(
              (s) => `<tr>
            <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-blue-600"><a href="symbols/${s.id}.html" class="hover:underline">${escapeHtml(s.name)}</a></td>
            <td class="px-6 py-4 whitespace-nowrap text-sm"><span class="${badgeClass(s.kind)}">${s.kind}</span></td>
            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500"><a href="files/${fileSlug(s.file)}.html" class="hover:text-blue-600 hover:underline">${escapeHtml(s.file)}</a></td>
            <td class="px-6 py-4 whitespace-nowrap text-sm font-mono text-gray-500 text-xs">${s.signature ? escapeHtml(s.signature) : "-"}</td>
          </tr>`,
            )
            .join("")}
        </tbody>
      </table>
    </div>`}
  `;

  return layout("Deprecated", "deprecated.html", body);
}

export function renderGovernancePage(
  archViolations: ArchViolationRow[],
  reaperFindings: ReaperFindingRow[],
  symbols: CodeSymbol[],
): string {
  const symbolMap = new Map(symbols.map((s) => [s.id, s]));

  const body = `
    <h1 class="text-3xl font-bold text-gray-900 mb-8 pb-4 border-b border-gray-200">Governance</h1>
    <p class="text-gray-600 mb-8">Architecture violations and code quality findings (Reaper).</p>

    <div id="arch" class="mb-12">
      <h2 class="text-2xl font-bold text-gray-900 mb-6">Architecture Violations</h2>
      ${archViolations.length === 0
        ? "<p class='text-gray-500'>No architecture violations.</p>"
        : `
      <div class="bg-white shadow overflow-x-auto sm:rounded-lg border border-gray-200">
        <table class="min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Rule</th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">File</th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Symbol</th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Severity</th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Message</th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">
            ${archViolations
              .map(
                (v) => {
                  const sym = v.symbol_id ? symbolMap.get(v.symbol_id) : undefined;
                  const symbolCell = sym
                    ? `<a href="symbols/${v.symbol_id}.html" class="text-blue-600 hover:underline">${escapeHtml(sym.name)}</a>`
                    : (v.symbol_id ? escapeHtml(v.symbol_id) : "-");
                  return `<tr>
                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">${escapeHtml(v.rule)}</td>
                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">${escapeHtml(v.file)}</td>
                <td class="px-6 py-4 whitespace-nowrap text-sm">${symbolCell}</td>
                <td class="px-6 py-4 whitespace-nowrap text-sm"><span class="px-2 py-0.5 rounded text-xs font-medium ${v.severity === "error" ? "bg-red-100 text-red-800" : "bg-yellow-100 text-yellow-800"}">${escapeHtml(v.severity)}</span></td>
                <td class="px-6 py-4 text-sm text-gray-600">${escapeHtml(v.message)}</td>
              </tr>`;
                },
              )
              .join("")}
          </tbody>
        </table>
      </div>`}
    </div>

    <div id="reaper" class="mb-12">
      <h2 class="text-2xl font-bold text-gray-900 mb-6">Code Quality (Reaper)</h2>
      ${reaperFindings.length === 0
        ? "<p class='text-gray-500'>No Reaper findings.</p>"
        : `
      <div class="bg-white shadow overflow-x-auto sm:rounded-lg border border-gray-200">
        <table class="min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Type</th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Target</th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Suggested action</th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Reason</th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">
            ${reaperFindings
              .map(
                (f) => {
                  const sym = symbolMap.get(f.target);
                  const targetCell = sym
                    ? `<a href="symbols/${f.target}.html" class="text-blue-600 hover:underline">${escapeHtml(sym.name)}</a>`
                    : escapeHtml(f.target);
                  return `<tr>
                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">${escapeHtml(f.type)}</td>
                <td class="px-6 py-4 whitespace-nowrap text-sm">${targetCell}</td>
                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">${escapeHtml(f.suggested_action)}</td>
                <td class="px-6 py-4 text-sm text-gray-600">${escapeHtml(f.reason)}</td>
              </tr>`;
                },
              )
              .join("")}
          </tbody>
        </table>
      </div>`}
    </div>
  `;

  return layout("Governance", "governance.html", body);
}

export function buildSearchIndex(symbols: CodeSymbol[]): {
  items: object[];
  facets: {
    kinds: Record<string, number>;
    tags: Record<string, number>;
    files: Record<string, number>;
  };
} {
  const items = symbols.map((s) => ({
    id: s.id,
    name: s.name,
    kind: s.kind,
    file: s.file,
    signature: s.signature ?? null,
    docRef: s.docRef ?? null,
    summary: s.summary ?? null,
    tags: s.tags ?? null,
    pattern: s.pattern ?? null,
    lastModified: s.lastModified ? formatDate(s.lastModified) : null,
    badgeClass: badgeClass(s.kind),
  }));

  const kinds: Record<string, number> = {};
  const tags: Record<string, number> = {};
  const files: Record<string, number> = {};

  for (const it of items) {
    kinds[it.kind] = (kinds[it.kind] ?? 0) + 1;
    if (Array.isArray(it.tags)) {
      for (const t of it.tags as string[]) {
        tags[t] = (tags[t] ?? 0) + 1;
      }
    }
    const seg = it.file && typeof it.file === "string" ? it.file.split("/")[0] || it.file : "root";
    files[seg] = (files[seg] ?? 0) + 1;
  }

  return { items, facets: { kinds, tags, files } };
}