import type { CodeSymbol } from "../indexer/symbol.types.js";
import type { DetectedPattern } from "../patterns/patternAnalyzer.js";
import type { RelationshipRow } from "../storage/db.js";
import { CSS } from "./styles.js";
import {
  fileSlug,
  buildMermaidForSymbol,
  buildMermaidForFile,
  buildMermaidOverview,
  buildMermaidTopConnected,
} from "./shared.js";

export { fileSlug };

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function escapeCodeBlocks(str: string): string {
  // For syntax highlighting, we need to escape HTML but preserve code structure
  return escapeHtml(str);
}

function badgeClass(kind: string): string {
  const map: Record<string, string> = {
    class: "badge-class",
    abstract_class: "badge-class",
    interface: "badge-interface",
    function: "badge-function",
    method: "badge-method",
    enum: "badge-enum",
    type: "badge-type",
  };
  return map[kind] ?? "badge-class";
}

function visibilityBadge(visibility?: string): string {
  if (!visibility) return "";
  const map: Record<string, string> = {
    public: "badge-public",
    protected: "badge-protected",
    private: "badge-private",
  };
  return `<span class="badge ${map[visibility] || "badge-public"}">${visibility}</span>`;
}

function layerBadge(layer?: string): string {
  if (!layer) return "";
  const map: Record<string, string> = {
    domain: "badge-layer-domain",
    application: "badge-layer-application",
    infrastructure: "badge-layer-infrastructure",
    presentation: "badge-layer-presentation",
    test: "badge-layer",
  };
  return `<span class="badge ${map[layer] || "badge-layer"}">${layer}</span>`;
}

function statusBadges(symbol: CodeSymbol): string {
  const badges = [];
  if (symbol.exported) badges.push(`<span class="badge badge-exported">exported</span>`);
  if (symbol.deprecated) badges.push(`<span class="badge badge-deprecated">deprecated</span>`);
  return badges.join(" ");
}

function nav(current: string, depth: number): string {
  const prefix = depth > 0 ? "../".repeat(depth) : "";
  const links = [
    [`${prefix}index.html`, "Dashboard"],
    [`${prefix}relationships.html`, "Relationships"],
    [`${prefix}patterns.html`, "Patterns"],
  ];
  const base = current.split("/").pop() ?? current;
  return `<nav>${links
    .map(([href, label]) =>
      base === href.split("/").pop()
        ? `<strong>${label}</strong>`
        : `<a href="${href}">${label}</a>`,
    )
    .join("")}</nav>`;
}

function layout(title: string, currentPage: string, body: string, depth = 0): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(title)} - doc-kit</title>
  <meta name="description" content="Documentation generated by doc-kit for your codebase">
  <script type="application/ld+json">${escapeHtml(
    JSON.stringify({
      "@context": "https://schema.org",
      "@type": "WebSite",
      name: "doc-kit",
      description: "Documentation generated by doc-kit for a codebase",
    }),
  )}</script>
  <style>${CSS}</style>
</head>
<body>
  <a class="skip-link" href="#content">Skip to content</a>
  ${nav(currentPage, depth)}
  <main id="content" role="main">
  ${body}
  </main>
  <footer>Generated by doc-kit</footer>
</body>
</html>`;
}

function formatDate(d?: Date): string | undefined {
  if (!d) return undefined;
  try {
    return d.toISOString();
  } catch {
    return String(d);
  }
}

export interface SiteData {
  symbols: CodeSymbol[];
  relationships: RelationshipRow[];
  patterns: DetectedPattern[];
  files: string[];
}

export function renderDashboard(data: SiteData): string {
  const { symbols, relationships, patterns, files } = data;

  const kindCounts: Record<string, number> = {};
  for (const s of symbols) {
    kindCounts[s.kind] = (kindCounts[s.kind] ?? 0) + 1;
  }

  // Layer counts
  const layerCounts: Record<string, number> = {};
  for (const s of symbols) {
    const layer = s.layer || "unknown";
    layerCounts[layer] = (layerCounts[layer] ?? 0) + 1;
  }

  // Top complex symbols
  const complexSymbols = symbols
    .filter((s) => s.metrics?.cyclomaticComplexity)
    .sort((a, b) => (b.metrics!.cyclomaticComplexity || 0) - (a.metrics!.cyclomaticComplexity || 0))
    .slice(0, 10);

  // Group files by directory
  const dirGroups: Record<string, { files: string[]; symbols: number }> = {};
  for (const file of files) {
    const dir = file.split("/")[0] || "root";
    if (!dirGroups[dir]) dirGroups[dir] = { files: [], symbols: 0 };
    dirGroups[dir].files.push(file);
  }
  for (const symbol of symbols) {
    const dir = symbol.file.split("/")[0] || "root";
    if (dirGroups[dir]) dirGroups[dir].symbols++;
  }

  // Overview graph
  const overviewGraph = buildMermaidOverview(symbols, relationships, true);

  const topLevel = symbols.filter((s) => !s.parent);

  const body = `
    <h1>doc-kit Documentation</h1>

    <div class="stats">
      <div class="stat">
        <div class="number">${files.length}</div>
        <div class="label">Files</div>
      </div>
      <div class="stat">
        <div class="number">${symbols.length}</div>
        <div class="label">Symbols</div>
      </div>
      <div class="stat">
        <div class="number">${relationships.length}</div>
        <div class="label">Relationships</div>
      </div>
      <div class="stat">
        <div class="number">${patterns.length}</div>
        <div class="label">Patterns</div>
      </div>
    </div>

    <h2>Architecture Layers</h2>
    <div class="layer-cards">
      ${Object.entries(layerCounts)
        .sort((a, b) => b[1] - a[1])
        .map(
          ([layer, count]) => `
        <div class="layer-card">
          <div class="number">${count}</div>
          <div class="label">${layer}</div>
        </div>`,
        )
        .join("")}
    </div>

    ${
      overviewGraph
        ? `
    <h2>Architecture Overview</h2>
    <div class="mermaid-container">
      <div class="mermaid">${overviewGraph}</div>
    </div>`
        : ""
    }

    <h2>Top Complex Symbols</h2>
    <table>
      <thead><tr><th scope="col">Name</th><th scope="col">File</th><th scope="col">Complexity</th><th scope="col">LOC</th></tr></thead>
      <tbody>
        ${complexSymbols
          .map((s) => {
            const complexity = s.metrics?.cyclomaticComplexity || 0;
            const loc = s.metrics?.linesOfCode || 0;
            return `<tr class="${complexity > 10 ? "complexity-high" : ""}">
            <td><a href="symbols/${s.id}.html">${escapeHtml(s.name)}</a></td>
            <td><a href="files/${fileSlug(s.file)}.html">${escapeHtml(s.file)}</a></td>
            <td>${complexity}</td>
            <td>${loc}</td>
          </tr>`;
          })
          .join("")}
      </tbody>
    </table>

    <h2>Symbol Kinds</h2>
    <div class="stats">
      ${Object.entries(kindCounts)
        .sort((a, b) => b[1] - a[1])
        .map(
          ([kind, count]) => `
        <div class="stat">
          <div class="number">${count}</div>
          <div class="label">${kind}</div>
        </div>`,
        )
        .join("")}
    </div>

    <h2>Files by Directory</h2>
    ${Object.entries(dirGroups)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(
        ([dir, { files: dirFiles, symbols: symbolCount }]) => `
      <details class="dir-group">
        <summary>${escapeHtml(dir)} <span class="dir-count">(${dirFiles.length} files, ${symbolCount} symbols)</span></summary>
        <ul>
          ${dirFiles
            .sort()
            .map((f) => `<li><a href="files/${fileSlug(f)}.html">${escapeHtml(f)}</a></li>`)
            .join("")}
        </ul>
      </details>`,
      )
      .join("")}

    <h2>Top-Level Symbols</h2>
    <table>
      <thead><tr><th scope="col">Name</th><th scope="col">Kind</th><th scope="col">File</th></tr></thead>
      <tbody>
        ${topLevel
          .sort((a, b) => a.name.localeCompare(b.name))
          .map(
            (s) => `<tr>
            <td><a href="symbols/${s.id}.html">${escapeHtml(s.name)}</a></td>
            <td><span class="badge ${badgeClass(s.kind)}">${s.kind}</span></td>
            <td><a href="files/${fileSlug(s.file)}.html">${escapeHtml(s.file)}</a></td>
          </tr>`,
          )
          .join("")}
      </tbody>
    </table>

    <h2>Search</h2>
    <div class="search-area">
      <div class="facets" id="facets">
        <div class="facet" id="facet-kinds"><strong>Kinds</strong><div class="facet-list"></div></div>
        <div class="facet" id="facet-tags"><strong>Tags</strong><div class="facet-list"></div></div>
        <div class="facet" id="facet-files"><strong>Files</strong><div class="facet-list"></div></div>
      </div>
      <div style="flex:1">
        <div role="search" aria-label="Symbol search">
          <input type="text" class="search-box" id="search" placeholder="Search symbols..." aria-label="Search symbols">
        </div>
        <ul class="search-results" id="results" role="region" aria-live="polite" aria-label="Search results"></ul>
      </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/fuse.js@6.6.2/dist/fuse.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
    <script>
      mermaid.initialize({startOnLoad:true,theme:'default',securityLevel:'loose'});

      var INDEX = null;
      var FUSE = null;

      function renderFacets(facets) {
        function renderList(containerId, map, keyName) {
          var el = document.getElementById(containerId).querySelector('.facet-list');
          el.innerHTML = '';
          Object.keys(map).sort().forEach(function(k){
            var id = containerId + '-' + k.replace(/[^a-z0-9]/gi,'_');
            var cb = document.createElement('input'); cb.type='checkbox'; cb.id=id; cb.dataset.value=k; cb.dataset.key=keyName;
            cb.addEventListener('change', function(){ doSearch(document.getElementById('search').value); });
            var label = document.createElement('label'); label.htmlFor = id; label.appendChild(cb); label.appendChild(document.createTextNode(' ' + k + ' ('+map[k]+')'));
            var div = document.createElement('div'); div.appendChild(label); el.appendChild(div);
          });
        }
        renderList('facet-kinds', facets.kinds, 'kind');
        renderList('facet-tags', facets.tags, 'tag');
        renderList('facet-files', facets.files, 'file');
      }

      function getSelectedFacets() {
        var checks = document.querySelectorAll('.facet input[type=checkbox]');
        var sel = { kinds: new Set(), tags: new Set(), files: new Set() };
        checks.forEach(function(ch){ if (ch.checked) { var k = ch.dataset.key; if (k==='kind') sel.kinds.add(ch.dataset.value); if (k==='tag') sel.tags.add(ch.dataset.value); if (k==='file') sel.files.add(ch.dataset.value); } });
        return sel;
      }

      function itemMatchesFacets(item, sel) {
        if (sel.kinds.size && !sel.kinds.has(item.kind)) return false;
        if (sel.files.size) {
          var p = item.file ? item.file.split('/')[0] : 'root';
          if (!sel.files.has(p)) return false;
        }
        if (sel.tags.size) {
          var itags = Array.isArray(item.tags) ? item.tags : [];
          var ok = false; for (var t of itags) { if (sel.tags.has(t)) { ok = true; break; } }
          if (!ok) return false;
        }
        return true;
      }

      function renderResults(results) {
        var r = document.getElementById('results'); r.textContent='';
        results.slice(0, 100).forEach(function(it){
          var li = document.createElement('li');
          var a = document.createElement('a'); a.href='symbols/'+it.id+'.html'; a.textContent=it.name; li.appendChild(a);
          li.appendChild(document.createTextNode(' '));
          var span = document.createElement('span'); span.className='badge '+it.badgeClass; span.textContent=it.kind; li.appendChild(span);
          if (it.signature) { li.appendChild(document.createTextNode(' - ')); var sig = document.createElement('code'); sig.textContent = it.signature; li.appendChild(sig); }
          if (it.summary) { li.appendChild(document.createTextNode(' — ' + it.summary)); }
          r.appendChild(li);
        });
      }

      function doSearch(q) {
        if (!INDEX) return;
        var sel = getSelectedFacets();
        var results = [];
        if (q && q.trim().length>0 && FUSE) {
          results = FUSE.search(q).map(function(r){ return r.item; });
        } else {
          results = INDEX.items.slice();
        }
        results = results.filter(function(it){ return itemMatchesFacets(it, sel); });
        renderResults(results);
      }

      fetch('search.json')
        .then(function (r) { return r.json(); })
        .then(function (data) {
          // Support two formats for search.json:
          // - legacy: an array of items (tests and older sites)
          // - current: { items: [], facets: { ... } }
          if (Array.isArray(data)) {
            INDEX = { items: data, facets: { kinds: {}, tags: {}, files: {} } };
            // Build simple facets from items
            for (const it of data) {
              INDEX.facets.kinds[it.kind] = (INDEX.facets.kinds[it.kind] ?? 0) + 1;
              const seg = it.file ? (typeof it.file === 'string' ? it.file.split('/')[0] || it.file : 'root') : 'root';
              INDEX.facets.files[seg] = (INDEX.facets.files[seg] ?? 0) + 1;
              if (Array.isArray(it.tags)) {
                for (const t of it.tags) INDEX.facets.tags[t] = (INDEX.facets.tags[t] ?? 0) + 1;
              }
            }
          } else {
            INDEX = data;
          }

          renderFacets(INDEX.facets);
          // Initialize Fuse
          try {
            FUSE = new Fuse(INDEX.items, { keys: [{ name: 'name', weight: 0.6 }, { name: 'signature', weight: 0.2 }, { name: 'summary', weight: 0.2 }], includeMatches: true, threshold: 0.35 });
          } catch (e) { console.warn('Fuse init failed', e); FUSE = null; }
          document.getElementById('search').addEventListener('input', function (e) { doSearch(e.target.value); });
        });
    </script>
  `;

  return layout("Dashboard", "index.html", body);
}

export function renderSymbolPage(
  symbol: CodeSymbol,
  allSymbols: CodeSymbol[],
  relationships: RelationshipRow[],
  sourceCode?: string,
): string {
  const children = allSymbols.filter((s) => s.parent === symbol.id);
  const outgoing = relationships.filter((r) => r.source_id === symbol.id);
  const incoming = relationships.filter((r) => r.target_id === symbol.id);

  // Extract source code snippet with syntax highlighting
  let sourceSnippet = "";
  if (sourceCode) {
    const lines = sourceCode.split("\n");
    const start = Math.max(0, symbol.startLine - 1);
    const end = Math.min(lines.length, symbol.endLine);
    const snippet = lines.slice(start, end);
    // Add line numbers and highlight current symbol line
    const symbolLine = symbol.startLine - 1;
    const numbered = snippet
      .map((line, i) => {
        const lineNum = start + i + 1;
        const isSymbolLine = lineNum === symbolLine;
        return `<span class="${isSymbolLine ? "highlight-line" : ""}">${String(lineNum).padStart(4)} | ${escapeHtml(line)}</span>`;
      })
      .join("\n");
    sourceSnippet = numbered;
  }

  // Breadcrumb navigation
  const breadcrumb = [
    '<a href="../index.html">Dashboard</a>',
    `<a href="../files/${fileSlug(symbol.file)}.html">${escapeHtml(symbol.file)}</a>`,
  ];
  if (symbol.parent) {
    const parent = allSymbols.find((s) => s.id === symbol.parent);
    if (parent) {
      breadcrumb.splice(1, 0, `<a href="${parent.id}.html">${escapeHtml(parent.name)}</a>`);
    }
  }
  breadcrumb.push(escapeHtml(symbol.name));

  // Per-symbol dependency graph
  const depGraph = buildMermaidForSymbol(symbol, allSymbols, relationships, "outgoing", true);
  // Per-symbol impact graph (who depends on me)
  const impactGraph = buildMermaidForSymbol(symbol, allSymbols, relationships, "incoming", true);

  const body = `
    <div class="breadcrumb">
      ${breadcrumb.map((item) => `<span>${item}</span>`).join('<span class="sep"></span>')}
    </div>

    <h1>
      ${visibilityBadge(symbol.visibility)}
      ${layerBadge(symbol.layer)}
      ${statusBadges(symbol)}
      <span class="badge ${badgeClass(symbol.kind)}">${symbol.kind}</span>
      ${escapeHtml(symbol.name)}
    </h1>

    <div class="card">
      <p><strong>File:</strong> <a href="../files/${fileSlug(symbol.file)}.html">${escapeHtml(symbol.file)}</a>:${symbol.startLine}-${symbol.endLine}</p>
      ${symbol.signature ? `<p><strong>Signature:</strong> <code>${escapeHtml(symbol.signature)}</code></p>` : ""}
      ${symbol.pattern ? `<p><strong>Pattern:</strong> ${escapeHtml(symbol.pattern)}</p>` : ""}
      ${symbol.metrics ? `<p><strong>Metrics:</strong> LOC: ${symbol.metrics.linesOfCode ?? "-"}, Complexity: ${symbol.metrics.cyclomaticComplexity ?? "-"}, Params: ${symbol.metrics.parameterCount ?? "-"}</p>` : ""}
      ${symbol.docRef ? `<p><strong>Docs:</strong> <a href="../${escapeHtml(symbol.docRef.replace(/\.md$/, ".html"))}">${escapeHtml(symbol.docRef)}</a></p>` : ""}
      ${symbol.summary ? `<p><strong>Summary:</strong> ${escapeHtml(symbol.summary)}</p>` : ""}
      ${symbol.tags ? `<p><strong>Tags:</strong> ${symbol.tags.map((t) => `<span class='tag'>${escapeHtml(t)}</span>`).join(" ")}</p>` : ""}
      ${symbol.lastModified ? `<p><strong>Last Updated:</strong> ${escapeHtml(formatDate(symbol.lastModified) ?? "")}</p>` : ""}
    </div>

    ${
      sourceSnippet
        ? `<h2>Source Code</h2>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/github.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js"></script>
    <pre><code class="language-typescript">${sourceSnippet}</code></pre>
    <script>hljs.highlightAll();</script>`
        : ""
    }

    ${
      children.length > 0
        ? `<h2>Members</h2>
    <table>
      <thead><tr><th scope="col">Name</th><th scope="col">Kind</th><th scope="col">Visibility</th><th scope="col">Signature</th></tr></thead>
      <tbody>
        ${children
          .map(
            (c) => `<tr>
          <td><a href="${c.id}.html">${escapeHtml(c.name)}</a></td>
          <td><span class="badge ${badgeClass(c.kind)}">${c.kind}</span></td>
          <td>${visibilityBadge(c.visibility)}</td>
          <td>${c.signature ? `<code>${escapeHtml(c.signature)}</code>` : "-"}</td>
        </tr>`,
          )
          .join("")}
      </tbody>
    </table>`
        : ""
    }

    ${(() => {
      const listeners = incoming.filter((r) => r.type === "listens_to");
      if (symbol.kind === "event" && listeners.length > 0) {
        return `<h2>Listeners</h2>
    <table>
      <thead><tr><th scope="col">Listener</th><th scope="col">File</th></tr></thead>
      <tbody>
        ${listeners
          .map((r) => {
            const source = allSymbols.find((s) => s.id === r.source_id);
            return `<tr>
          <td>${source ? `<a href="${source.id}.html">${escapeHtml(source.name)}</a>` : r.source_id}</td>
          <td>${source ? `<a href="../files/${fileSlug(source.file)}.html">${escapeHtml(source.file)}</a>` : "-"}</td>
        </tr>`;
          })
          .join("")}
      </tbody>
    </table>`;
      }
      return "";
    })()}

    ${(() => {
      const listensTo = outgoing.filter((r) => r.type === "listens_to");
      if (symbol.kind === "listener" && listensTo.length > 0) {
        return `<h2>Listens to</h2>
    <table>
      <thead><tr><th scope="col">Event</th><th scope="col">File</th></tr></thead>
      <tbody>
        ${listensTo
          .map((r) => {
            const target = allSymbols.find((s) => s.id === r.target_id);
            return `<tr>
          <td>${target ? `<a href="${target.id}.html">${escapeHtml(target.name)}</a>` : r.target_id}</td>
          <td>${target ? `<a href="../files/${fileSlug(target.file)}.html">${escapeHtml(target.file)}</a>` : "-"}</td>
        </tr>`;
          })
          .join("")}
      </tbody>
    </table>`;
      }
      return "";
    })()}

    ${
      depGraph
        ? `<h2>Dependencies</h2>
    <div class="mermaid-container">
      <div class="mermaid">${depGraph}</div>
    </div>`
        : ""
    }

    ${
      outgoing.length > 0
        ? `<table>
      <thead><tr><th scope="col">Target</th><th scope="col">Type</th></tr></thead>
      <tbody>
        ${outgoing
          .map((r) => {
            const target = allSymbols.find((s) => s.id === r.target_id);
            return `<tr>
          <td>${target ? `<a href="${target.id}.html">${escapeHtml(target.name)}</a>` : r.target_id}</td>
          <td>${r.type}</td>
        </tr>`;
          })
          .join("")}
      </tbody>
    </table>`
        : ""
    }

    ${
      impactGraph
        ? `<h2>Impact (depended by)</h2>
    <div class="mermaid-container">
      <div class="mermaid">${impactGraph}</div>
    </div>`
        : ""
    }

    ${
      incoming.length > 0
        ? `<table>
      <thead><tr><th scope="col">Source</th><th scope="col">Type</th></tr></thead>
      <tbody>
        ${incoming
          .map((r) => {
            const source = allSymbols.find((s) => s.id === r.source_id);
            return `<tr>
          <td>${source ? `<a href="${source.id}.html">${escapeHtml(source.name)}</a>` : r.source_id}</td>
          <td>${r.type}</td>
        </tr>`;
          })
          .join("")}
      </tbody>
    </table>`
        : ""
    }

    <script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
    <script>mermaid.initialize({startOnLoad:true,theme:'default',securityLevel:'loose'});</script>
  `;

  return layout(symbol.name, "", body, 1);
}

export function renderFilePage(
  filePath: string,
  symbols: CodeSymbol[],
  sourceCode?: string,
  relationships?: RelationshipRow[],
  allSymbols?: CodeSymbol[],
): string {
  const topLevel = symbols.filter((s) => !s.parent);

  // File summary stats
  const totalSymbols = symbols.length;
  const totalLOC = sourceCode ? sourceCode.split("\n").length : 0;
  const avgComplexity =
    symbols
      .filter((s) => s.metrics?.cyclomaticComplexity)
      .reduce((sum, s) => sum + (s.metrics!.cyclomaticComplexity || 0), 0) / symbols.length || 0;

  const kindCounts: Record<string, number> = {};
  for (const s of symbols) {
    kindCounts[s.kind] = (kindCounts[s.kind] ?? 0) + 1;
  }

  // File relationships graph
  let fileGraph = "";
  if (relationships && allSymbols) {
    fileGraph = buildMermaidForFile(filePath, allSymbols, relationships, true);
  }

  const body = `
    <h1>${escapeHtml(filePath)}</h1>

    <div class="file-summary">
      <div class="stat">
        <div class="number">${totalSymbols}</div>
        <div class="label">Total Symbols</div>
      </div>
      <div class="stat">
        <div class="number">${totalLOC}</div>
        <div class="label">Lines of Code</div>
      </div>
      <div class="stat">
        <div class="number">${avgComplexity.toFixed(1)}</div>
        <div class="label">Avg Complexity</div>
      </div>
      <div class="stat">
        <div class="number">${Object.keys(kindCounts).length}</div>
        <div class="label">Symbol Types</div>
      </div>
    </div>

    ${
      fileGraph
        ? `
    <h2>File Relationships</h2>
    <div class="mermaid-container">
      <div class="mermaid">${fileGraph}</div>
    </div>`
        : ""
    }

    <h2>Symbols by Kind</h2>
    <div class="stats">
      ${Object.entries(kindCounts)
        .sort((a, b) => b[1] - a[1])
        .map(
          ([kind, count]) => `
        <div class="stat">
          <div class="number">${count}</div>
          <div class="label">${kind}</div>
        </div>`,
        )
        .join("")}
    </div>

    <h2>All Symbols</h2>
    <table>
      <thead><tr><th scope="col">Name</th><th scope="col">Kind</th><th scope="col">Visibility</th><th scope="col">Lines</th><th scope="col">Signature</th></tr></thead>
      <tbody>
        ${topLevel
          .sort((a, b) => a.startLine - b.startLine)
          .map((s) => {
            const children = symbols.filter((c) => c.parent === s.id);
            return `<tr>
          <td><a href="../symbols/${s.id}.html">${escapeHtml(s.name)}</a></td>
          <td><span class="badge ${badgeClass(s.kind)}">${s.kind}</span></td>
          <td>${visibilityBadge(s.visibility)}</td>
          <td>${s.startLine}-${s.endLine}</td>
          <td>${s.signature ? `<code>${escapeHtml(s.signature)}</code>` : "-"}</td>
        </tr>
        ${children
          .map(
            (c) => `<tr>
          <td style="padding-left:2rem"><a href="../symbols/${c.id}.html">${escapeHtml(c.name)}</a></td>
          <td><span class="badge ${badgeClass(c.kind)}">${c.kind}</span></td>
          <td>${visibilityBadge(c.visibility)}</td>
          <td>${c.startLine}-${c.endLine}</td>
          <td>${c.signature ? `<code>${escapeHtml(c.signature)}</code>` : "-"}</td>
        </tr>`,
          )
          .join("")}`;
          })
          .join("")}
      </tbody>
    </table>

    ${
      sourceCode
        ? `<h2>Full Source</h2>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/github.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js"></script>
    <pre><code class="language-typescript">${escapeCodeBlocks(sourceCode)}</code></pre>
    <script>hljs.highlightAll();</script>`
        : ""
    }

    <script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
    <script>mermaid.initialize({startOnLoad:true,theme:'default',securityLevel:'loose'});</script>
  `;

  return layout(filePath, "", body, 1);
}

export function renderRelationshipsPage(
  relationships: RelationshipRow[],
  symbols: CodeSymbol[],
): string {
  const symbolMap = new Map(symbols.map((s) => [s.id, s]));

  // Group relationships by type for summary
  const byType: Record<string, number> = {};
  for (const r of relationships) {
    byType[r.type] = (byType[r.type] ?? 0) + 1;
  }

  // Top connected symbols graph
  const topConnectedGraph = buildMermaidTopConnected(symbols, relationships, 30, true);

  const body = `
    <h1>Relationships</h1>

    <div class="stats">
      ${Object.entries(byType)
        .sort((a, b) => b[1] - a[1])
        .map(
          ([type, count]) => `
        <div class="stat">
          <div class="number">${count}</div>
          <div class="label">${type}</div>
        </div>`,
        )
        .join("")}
    </div>

    ${
      topConnectedGraph
        ? `
    <h2>Architecture Overview (Top 30 Connected)</h2>
    <div class="mermaid-container">
      <div class="mermaid">${topConnectedGraph}</div>
    </div>`
        : ""
    }

    <p>Each symbol page contains focused dependency and impact graphs. Below is the full relationship table.</p>

    <h2>All Relationships</h2>
    <input type="text" class="table-filter" id="relationship-filter" placeholder="Filter relationships...">
    <table id="relationships-table">
      <thead><tr><th>Source</th><th>Type</th><th>Target</th></tr></thead>
      <tbody>
        ${relationships
          .map((r) => {
            const source = symbolMap.get(r.source_id);
            const target = symbolMap.get(r.target_id);
            return `<tr data-source="${escapeHtml(source?.name || r.source_id)}" data-type="${r.type}" data-target="${escapeHtml(target?.name || r.target_id)}">
          <td>${source ? `<a href="symbols/${source.id}.html">${escapeHtml(source.name)}</a>` : r.source_id}</td>
          <td>${r.type}</td>
          <td>${target ? `<a href="symbols/${target.id}.html">${escapeHtml(target.name)}</a>` : r.target_id}</td>
        </tr>`;
          })
          .join("")}
      </tbody>
    </table>

    <script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
    <script>
      mermaid.initialize({startOnLoad:true,theme:'default',securityLevel:'loose'});

      // Client-side table filtering
      document.getElementById('relationship-filter').addEventListener('input', function(e) {
        const filter = e.target.value.toLowerCase();
        const rows = document.querySelectorAll('#relationships-table tbody tr');

        rows.forEach(row => {
          const source = row.dataset.source.toLowerCase();
          const type = row.dataset.type.toLowerCase();
          const target = row.dataset.target.toLowerCase();

          const matches = source.includes(filter) || type.includes(filter) || target.includes(filter);
          row.style.display = matches ? '' : 'none';
        });
      });
    </script>
  `;

  return layout("Relationships", "relationships.html", body);
}

export function renderPatternsPage(patterns: DetectedPattern[], symbols: CodeSymbol[]): string {
  const symbolMap = new Map(symbols.map((s) => [s.id, s]));

  const body = `
    <h1>Detected Patterns</h1>

    ${
      patterns.length === 0
        ? "<p>No patterns detected.</p>"
        : patterns
            .map(
              (p) => `
      <div class="card">
        <h3>${escapeHtml(p.kind)} <small>(confidence: ${(p.confidence * 100).toFixed(0)}%)</small></h3>
        <p><strong>Symbols:</strong> ${p.symbols
          .map((id) => {
            const s = symbolMap.get(id);
            return s ? `<a href="symbols/${s.id}.html">${escapeHtml(s.name)}</a>` : id;
          })
          .join(", ")}</p>
        ${
          p.violations.length > 0
            ? `<p><strong>Violations:</strong></p><ul>${p.violations
                .map((v) => `<li>${escapeHtml(v)}</li>`)
                .join("")}</ul>`
            : ""
        }
      </div>`,
            )
            .join("")
    }
  `;

  return layout("Patterns", "patterns.html", body);
}

export function buildSearchIndex(symbols: CodeSymbol[]): {
  items: object[];
  facets: {
    kinds: Record<string, number>;
    tags: Record<string, number>;
    files: Record<string, number>;
  };
} {
  const items = symbols.map((s) => ({
    id: s.id,
    name: s.name,
    kind: s.kind,
    file: s.file,
    signature: s.signature ?? null,
    docRef: s.docRef ?? null,
    summary: s.summary ?? null,
    tags: s.tags ?? null,
    pattern: s.pattern ?? null,
    lastModified: s.lastModified ? formatDate(s.lastModified) : null,
    badgeClass: badgeClass(s.kind),
  }));

  const kinds: Record<string, number> = {};
  const tags: Record<string, number> = {};
  const files: Record<string, number> = {};

  for (const it of items) {
    kinds[it.kind] = (kinds[it.kind] ?? 0) + 1;
    if (Array.isArray(it.tags)) {
      for (const t of it.tags as string[]) {
        tags[t] = (tags[t] ?? 0) + 1;
      }
    }
    // file prefix: first path segment
    const seg = it.file && typeof it.file === "string" ? it.file.split("/")[0] || it.file : "root";
    files[seg] = (files[seg] ?? 0) + 1;
  }

  return { items, facets: { kinds, tags, files } };
}
